### ISSUE TITLE
Xcode project for MacOS app

### ISSUE THREAD

**Issue by eldare** [beeware/briefcase#1025]
### What is the problem or limitation you are having?

I would like to have better control over the MacOS app.
Currently Briefcase uses a ready MacOS bundle, not sure why it's like that though, is it intentional?

### Describe the solution you'd like

I would like an Xcode project created from MacOS app, just like it does for iOS app.

### Describe alternatives you've considered

No alternative. I would like full control over the MacOS xcode project.

### Additional context

thank you.

**Comment by mhsmith** [comment]
> Currently Briefcase uses a ready MacOS bundle, not sure why it's like that though, is it intentional?

Yes: it speeds up the build for simple projects, and makes it possible to build apps without having a full Xcode install. 

However, Briefcase can also create a full Xcode project if you want. Just add the words `macos xcode` to each command. For example, instead of running `briefcase create`, run `briefcase create macos xcode`.
