### ISSUE TITLE
Add APK packaging output for Android Gradle backend

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1136]
### What is the problem or limitation you are having?

When doing ad-hoc distribution of an Android app, you will generally want to pass around a release APK file. At present, Briefcase compiles a debug APK for `briefcase run`, but doesn't produce a release APK, and doesn't put that APK somewhere that is accessible.

### Describe the solution you'd like

`briefcase package android` shoul have a `-p apk` option, which will (a) compile a release APK, and (b) copy that release APK to the `dist` folder.

### Describe alternatives you've considered

1. Only support Play Store distribution
2. Manually build release artefacts by invoking gradle directly
3. Distribute debug artefacts copying from the gradle build file.

### Additional context

In the meantime - if you *do* want an APK, debug APK created by Briefcase as a result of calling `briefcase run android` will be in `build/<app name>/android/gradle/app/build/outputs/apk/debug/app-debug.apk`.

**Comment by MarkusPiotrowski** [comment]
1. Creating a release APK and putting it to the `dist` folder seems easy to do. But this release APK would be unaligned and unsigned. Would this be OK or should (optional) aligning and signing also be integrated? If the latter, I wonder if the required tools (`zipalign` and `apksigner`) are available from within BeeWare/briefcase or must be defined somewhere for download?
2. Should the debug apk also be exposed in `dist`? I would find this useful because that one can be installed on other devices for testing (opposed to the unsigned release apk).

**Comment by freakboy3742** [comment]
1. The APK generated into the `dist` folder should be usable/distributable as-is without any additional modifications, except *possibly* for signing. If signing *can* be integrated as well, that's an added bonus. It would also be acceptable for signing to be a separate PR, with the only mention of signing in this PR being something in documentation mentioning that it is needed.
2. I guess exposing the debug APK as well makes sense; my inclination would be to treat it as a separate "format" (i.e. `-p debug-apk`), and share as much logic as possible between the "apk" and "debug-apk" output format generators.
