### ISSUE TITLE
RTD is Showing Docs for `v0.3.13` as `stable` After Release of `v0.3.14`

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1182]
### Describe the bug

The RTD build for `v0.3.14` [failed](https://readthedocs.org/projects/briefcase/builds/20086650/) on a misspelling for Pygame; although, this has since been [resolved](https://github.com/beeware/briefcase/commit/d2824a97c448b5a2a7c2716e76e57cd87f15c7db).

Looking back at the `docs` branch on `rmartin16/briefcase`, the commits that added Pygame support are indeed missing. I suppose this is an uncommon example of where the "Require branches to be up to date before merging" setting would have been quite useful.

### Steps to reproduce

See https://briefcase.readthedocs.io/en/stable

### Expected behavior

Show docs for `v0.3.14`.

I'm not sure the recommended way to resolve this; the only apparent way that occurs to me is moving the tag for `v0.3.14`...but that doesn't seem great for plenty of other reasons...

### Environment

n/a

**Comment by freakboy3742** [comment]
Well... that bites. 

As an immediate workaround, I've updated RTD to show "latest". I'll leave this ticket open as a TODO reminder to revert that setting for the 0.3.15 release.

The root cause here seems to be that the RTD build failure isn't exposed as a blocking issue when doing a release. On a PR, an RTD build failure is visualised as a blocking item; however, that doesn't surface on release tags.

I can see a couple of possible systemic fixes:

1) As @rmartin16 suggests, add the "require branches to be up to date" setting. This works, but would be cumbersome when we have a lot of PRs to merge (as we do on Monday mornings when Dependabot runs, or during sprint conditions). Given that our test suite takes ~20 minutes to run, it would be desirable to minimise this sort of rebuild churn.
2) Enable the merge queue. That should minimize the number of builds that are done, but I'm not sure it's *that* much better.
3) Add a manual step to the release documentation to check the status of the RTD build before cutting the final release. This would prevent the problem, but would have also caused a headache in this case, as the 0.3.14 build would have been successfully pushed to TestPyPI, preventing a second 0.3.14 build from being created.
4) Add a docs build step to the release CI. This technically duplicates what RTD is doing, but it would surface the failure explicitly in Github's processes, and avoids the (3) problem because a successful docs lint & build would be a pre-requisite of pushing to TestPyPI.

Of these, (4) seems like the most likely to avoid this problem again in future, with a minimum of rebuild churn on end-users. Thoughts?

And - whatever we decide, we should do the same on Toga and Rubicon.

**Comment by rmartin16** [comment]
(timing of events not fully thought through....but this should work in theory at least...)

I think (4) is the good choice. However, RTD appears to provide an API to read [build statuses](https://docs.readthedocs.io/en/stable/api/v3.html#version-detail).

We could use this to detect a build failure in the release process.
```bash
~ 
❯ curl --silent -H "Authorization: Token $TOKEN" https://readthedocs.org/api/v3/projects/briefcase/versions/v0.3.13/ | jq .built
true

~ 
❯ curl --silent -H "Authorization: Token $TOKEN" https://readthedocs.org/api/v3/projects/briefcase/versions/v0.3.14/ | jq .built
false
```

**Comment by freakboy3742** [comment]
With the release of 0.3.15, we can now set RTD to point at stable again.
