### ISSUE TITLE
Add support for creating macOS installers

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1184]
### What is the problem or limitation you are having?

Briefcase currently produces bare `.app` bundles, or `.dmg` bundles. They can be executed as-is, or dragged into the Applications folder.

However, macOS also supports the creation of installer packages. These aren't needed for simple apps, but if an app requires a post install script, or there are multiple resources files that need to be installed, an installer may be required.

### Describe the solution you'd like

Briefcase should support the creation of installers as a packaging format.

`briefcase package macOS -p installer`

Ideally, this would also allow for the addition of a user-supplied post-install script to the installer.

### Describe alternatives you've considered

Do nothing, and don't support pre/post install scripts as a use case.

### Additional context

[This StackOverflow post](https://stackoverflow.com/a/11487658) includes a fairly detailed rundown of building an installer.

If an installer with a post-install script can be generated, it could provide a path for #556 on macOS. A command line app is an installed app that puts itself on the command line. The Python.org macOS installer is an example of this, adding `/Library/Frameworks/Python.framework/Versions/3.X/bin` to the path. Installing an app bundle in `~/Applications`, then adding `~/Applications/My App.app/Contents/MacOS/myapp` to the path would provide a packaged command-line app for macOS.

**Comment by michelcrypt4d4mus** [comment]
+1

**Comment by freakboy3742** [comment]
@michelcrypt4d4mus If you're interested in this feature, there is a draft implementation in #1781.

**Comment by michelcrypt4d4mus** [comment]
thanks - i'm interested / willing to test but being new to briefcase it's not immediately clear to me how to use the PR. what i specifically want to do is this:

1. use briefcase to convert a server only / non-GUI app to a macos `.app`. I've already managed to do this (and it was pretty quick and easy - bravo team briefcase).
2. build an installer that lets me configure a `launchd` daemon process (this is why I'm interested in this issue here). the goal is to have the app run as any other `launchd` managed process in `~/Library/LaunchAgents/`. i already already have scripts that set this up successfully (configure `.plist` files, call `launchctl` etc) in my project's development environment so what i'm hoping briefcase can help me with is creating an installer that will run this additional setup (placing `.plist` file, calling `launchctl bootstrap`).

the _ultimate_ goal is to package this server side app and another GUI / front end executable together into a single `.app` file... but one step at a time.

**Comment by freakboy3742** [comment]
In terms of testing the PR: the Briefcase docs have a guide on setting up a development environment. If you check out the PR branch, and use that branch in your development environment, you can test the code.

We haven't tackled launchd as part of that PR, though. #1781 is purely about adding support for command line apps; but as part of that, we've added .pkg installers because installing a command line app needs a post-install script to add the app to the command line.

Adding support for "add to auto-started apps" would be a separate feature request that would need to land after #1781 has landed. I've opened #1803 to track this feature request.

**Comment by michelcrypt4d4mus** [comment]
yeah i'm aware briefcase doesn't support that directly yet so what i'm hoping to do is use briefcase to build the Xcode project etc. and then go in there and manually tweak stuff from there. maybe if it goes well and i figure out how to make it work i can contribute a PR to briefcase re: #1803.
