### ISSUE TITLE
Problem getting an app with bcrypt to run

### ISSUE THREAD

**Issue by boxed** [beeware/briefcase#1189]
### Describe the bug

I have a very simple app I'm trying to write that uses paramiko for SSH. It crashes on startup in the simulator with an ImportError. 

### Steps to reproduce

This is my code:

```py
import paramiko
import toga
from paramiko.client import (
    WarningPolicy,
)
from toga.style import Pack
from toga.style.pack import COLUMN


class RebootShow(toga.App):

    def startup(self):
        """
        Construct and show the Toga application.

        Usually, you would add your application to a main content box.
        We then create a main window (with a name matching the app), and
        show the main window.
        """
        self.reboot_show(1)
        main_box = toga.Box(style=Pack(direction=COLUMN))

        button = toga.Button(
            "Reboot Show",
            on_press=self.reboot_show,
            style=Pack(padding=5)
        )

        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def reboot_show(self, widget):
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(WarningPolicy)
        client.connect('******', username='boxed', password='******')
        ssh_stdin, ssh_stdout, ssh_stderr = client.exec_command("""osascript -e 'tell app "System Events" to restart'""")
        print(ssh_stdout.read(), ssh_stderr.read())


def main():
    return RebootShow()
```
with hostname and password censored.

### Expected behavior

No crash

### Environment

- Operating System: macOS
- Python version: 3.9. Also tried 3.10 before.
- Software versions: 
  - Briefcase: 0.3.14
  - Toga: 0.3.1

### Logs

[briefcase.2023_04_16-19_52_55.run.log](https://github.com/beeware/briefcase/files/11243064/briefcase.2023_04_16-19_52_55.run.log)

**Comment by rmartin16** [comment]
> https://github.com/beeware/briefcase/files/11243064/briefcase.2023_04_16-19_52_55.run.log

@boxed, is this the right log file?

This one is documenting a device name issue:
```
Invalid device device name '00008101-000A21A11A30001E'
```

**Comment by boxed** [comment]
Ah crap. That's the other issue yea. This is a fresh log file for this issue (I deleted all other logs before :P)

[briefcase.2023_04_16-20_53_11.run.log](https://github.com/beeware/briefcase/files/11243157/briefcase.2023_04_16-20_53_11.run.log)

**Comment by rmartin16** [comment]
Thanks. My suspicion is you're not using `bcrypt` from https://anaconda.org/beeware/bcrypt.

Your log shows the latest version being installed....which would've come from pypi.org:
```
Using cached bcrypt-4.0.1.tar.gz
```

When I first tried to run your app in the OP, it failed because I don't have rust installed or anything. (I presume you have the prerequisites installed to build `bcrypt`.) That was when I noticed the `bcrypt` version. Once I added `bcrypt==3.1.7` to `requires` in `pyproject.toml`, the build finished and I could run the app.

Notably, though, this would limit your app to `paramiko==2.12` for now.

**Comment by freakboy3742** [comment]
Aside from the version problem that @rmartin16 has pointed out, this app will also fail *because* it's using paramiko. 

iOS, Android and Web deployments don't have support for subprocesses because of the sandboxing model they provide. You can only use threads.

Even if it did work... To the best of my knowledge, "osascript" doesn't exist on iPhones, either.

**Comment by freakboy3742** [comment]
/me facepalms... paramiko is an SSH client, so this is running `osascript` on the remote machine. As long as paramiko isn't using subprocesses, it should be fine.

**Comment by boxed** [comment]
Oh. Interesting. I don't care about the paramiko version or the bcrypt version (I think!). 

I changed to use the specific versions of bcrypt and paramiko as suggested, and I got further I think:

```
  File "/Users/boxed/Library/Developer/CoreSimulator/Devices/5A1148C9-9857-4B28-9DB6-8DFAC7D270D7/data/Containers/Bundle/Application/2C71ACA0-266C-401C-BCAF-5A55DA74A2E8/RebootShow.app/app_packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/Users/boxed/Library/Developer/CoreSimulator/Devices/5A1148C9-9857-4B28-9DB6-8DFAC7D270D7/data/Containers/Bundle/Application/2C71ACA0-266C-401C-BCAF-5A55DA74A2E8/RebootShow.app/app_packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ModuleNotFoundError: No module named '_cffi_backend'
Application has crashed!
```

I locked `cffi` to the version on anaconda too as a cargo cult idea, but that didn't change matters.

**Comment by freakboy3742** [comment]
Hrm - that's more interesting bug - it suggests the bcrypt module isn't working as expected. I'll need to dig into this some more. 

Unfortunately, I'm about to jump on a plane to head to PyCon US, so I probably won't be able to look into this for at least a couple of days. In case I do get a chance - you're using `bcrypt==3.1.7`, correct?

**Comment by boxed** [comment]
Correct

**Comment by rmartin16** [comment]
FWIW....the app in the OP runs for me on the iOS simulator for iPhone 14 Pro using Python 3.10. (Although, I modified it to just `echo $PATH` on a local linux machine.)

I would try to confirm that the package of `cffi` being used is from Anaconda's package server. I would expect Anaconda's server to take precedence since they are both advertising the same latest version. Although, I suppose it's possible `pip` is picking up a cached version of pypi.org's package maybe.

If you upload another log file, I'd be happy to take a look.

**Comment by boxed** [comment]
[briefcase.2023_04_17-20_12_03.run.log](https://github.com/beeware/briefcase/files/11254158/briefcase.2023_04_17-20_12_03.run.log)

**Comment by rmartin16** [comment]
> [briefcase.2023_04_17-20_12_03.run.log](https://github.com/beeware/briefcase/files/11254158/briefcase.2023_04_17-20_12_03.run.log)

Thanks. Unfortunately, the Briefcase command for that log doesn't include `-r` so none of the information about the requirements is included.

I was able to confirm `paramiko` works for me with simulated iPhone 14 plus like you used; although, while yours is using iOS 16.4, my simulator is using iOS 16.1. I'm also running on x86 (albeit virtualized) while you're using ARM.

I'd also try deleting the `build` directory in your project to ensure the build environment hasn't been tainted by any previous runs.

**Comment by boxed** [comment]
huh. I did `rm -rf build/` and rebuilt with the `-r` flag. The app starts.

**Comment by boxed** [comment]
Maybe. But I ran with `-r -d` which shows it downloading the dependency. My spidey sense is going off :P

**Comment by mhsmith** [comment]
If this happens again with Briefcase 0.3.14 or 15, please comment on this issue. If you're using Briefcase 0.3.16 or later, iOS support has changed significantly, so it would be better to create a separate issue.
