### ISSUE TITLE
Add support for OpenSuSE

### ISSUE THREAD

**Issue by Cimbali** [beeware/briefcase#1416]
If you run Briefcase on OpenSuSE, you currently get an error:

### Describe the bug

Running a built app fails with:
```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Install path: <a project specific path>
Pre-initializing Python runtime...
PYTHONPATH:
- /usr/lib/python3.11
- /usr/lib/python3.11/lib-dynload
- <some project specific paths>
Configure argc/argv...
Initializing Python runtime...
ModuleNotFoundError: No module named 'encodings'
```

And we have:
```
> python3.11 -c 'import encodings; print(encodings.__file__)'
/usr/lib64/python3.11/encodings/__init__.py
```

Note the path `/usr/lib64/python3.11` is not in PYTHONPATH (`lib64` instead of `lib`).

### Steps to reproduce

1. Get the basic template
2. Run `briefcase run`

### Expected behavior

Building picks up the paths required for python to run.

### Environment

- Operating System: OpenSUSE
- Python version: 3.11
- Software versions:
  - Briefcase: 0.3.15
  - Toga: 0.3.1

**Comment by Cimbali** [comment]
Obviously I’ve tried setting `PYTHONPATH` in the environment but to no avail. I should also mention the python install is absolutely fine, and the app runs with `briefcase dev`

**Comment by freakboy3742** [comment]
Thanks for the report - this appears to be an OpenSuSE specific detail. Unfortunately, we don't currently advertise support for OpenSuSE.

That said - adding support shouldn't be that difficult. 

The immediate cause of the problem you're seeing is that OpenSuSE isn't identifying a vendor base; and as a result, it's *not* working out that OpenSuSE is using the `/usr/lib64` folder.

I think this will stem from [This line in the briefcase template](https://github.com/beeware/briefcase-linux-system-template/blob/main/cookiecutter.json#L22), and/or [this section of platform identification code](https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/linux/__init__.py#L102). There will be a related issue when you get to packaging because briefcase [won't know what packaging format to use](https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/linux/system.py#L815).

The changes needed are:
1. Adding an extra block to identify SuSE as a vendor base, 
2. Include SuSE in the list of RPM-alike platforms, 
3. Modify the template so that it identifies SuSE as needing the lib64 folder
4. Adding OpenSuSE to the list of Linux distros that are known to support RPM.

I'm modifying the ticket to be a feature request for OpenSUSE support; if you want to try your hand at a fix, you're more than welcome to take a swing - we're here to provide help if you need it.
