### ISSUE TITLE
Impossible to change the Android Application Icon 

### ISSUE THREAD

**Issue by foxopop** [beeware/briefcase#1424]
### Describe the bug

I have changed all the icon.ico and <application>.ico files, to change the design of the logo.
But in Android, the icon always looks like the original bee !

I also tried to change the icon name in the pyproject.toml :

[tool.briefcase.app.MonAppli]
<...>
icon = "resources/MonAppli"
<...>
requires = [
]

### Steps to reproduce

1. Change the logo
2. Generate the application for Android
3. Look on the phone the list of all the applications
4. See error : the logo hasn't change : it's always the original bee icon

### Expected behavior

I was expecting to see my new logo, or en error message if the things were not well done.

### Environment

- Operating System: Windows 10
- Python version: 
- Software versions:
toga                          0.2.15
toga-android                  0.3.0.dev38
toga-core                     0.3.0.dev38
toga-winforms                 0.3.0.dev38
briefcase                     0.3.10
Python 3.10.6

### Logs

```

```

**Comment by freakboy3742** [comment]
It is definitely possible to change the icon of an Android app - the [Toga Testbed](https://github.com/beeware/toga/tree/main/testbed) and [Travel Tips](https://github.com/freakboy3742/traveltips) are two examples of apps that have custom icons.

If you're not seeing your custom icon, the problem is either:
1. You haven't provided an icon in the multiple formats required by Android. 
2. You haven't run `briefcase update android --update-resources` since changing your `pyproject.toml` file.

Based on the configuration you've provided, your build and/or update logs should contain a message that says something like:
```
[MonAppli] Updating application resources...
Unable to find resources/MonAppli-round-48.png for 48px round application icon; using default
Unable to find resources/MonAppli-round-72.png for 72px round application icon; using default
Unable to find resources/MonAppli-round-96.png for 96px round application icon; using default
Unable to find resources/MonAppli-round-144.png for 144px round application icon; using default
Unable to find resources/MonAppli-round-192.png for 192px round application icon; using default
Unable to find resources/MonAppli-square-48.png for 48px square application icon; using default
Unable to find resources/MonAppli-square-72.png for 72px square application icon; using default
Unable to find resources/MonAppli-square-96.png for 96px square application icon; using default
Unable to find resources/MonAppli-square-144.png for 144px square application icon; using default
Unable to find resources/MonAppli-square-192.png for 192px square application icon; using default
```

That tells you the 10 icon files that you need to provide for Android. If briefcase is finding the icon files, you'll get a success message rather than the "unable to find" message.

If the icon setting was present before running `create` for the first time, this message would have been displayed then, as well.

Also - if your environment description is correct (briefcase 0.3.10, toga 0.2.15...) I'd strongly suggest updating briefcase. You're 5 versions (and almost a year) behind the current Briefcase version, and there have been a lot of bug fixes in that time. I don't think any of those bugs relate to icons, though.

**Comment by foxopop** [comment]
Thanks for your help. The problem solved after upgrading briefcase ans toga.
