### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by wafaa09** [beeware/briefcase#1467]
### Describe the bug

Hello! I am attempting to import plotly and feel I have followed the steps correctly, however I am still receiving a message saying the module cannot be found. 

The steps I followed are as follows:

1. Installed plotly. 
2. Went to my pyproject.toml and added 'plotly==5.17.0' to the 'requires' under '[tool.briefcase.app.codnexlab]', '[tool.briefcase.app.codnexlab.iOS]', and '[tool.briefcase.app.codnexlab.android]'.
3. Updated briefcase by running briefcase update -r
4. ran briefcase run android --log

I got an error at the end of running the --log stating the 'Android emulator was unable to start!' Did I do something wrong? The log provided is from step 4. Also, I did not have an android file in my folder until I ran the log. is it okay to delete the android file that was created? 

### Steps to reproduce

When running briefcase run, I get an error stating 'ModuleNotFoundError: No module named 'plotly' '

### Expected behavior

I would like to run the plotly program.

### Screenshots

here is my pyproject.toml

[tool.briefcase.app.codnexlab]
icon = "src/codnexlab/resources/codnexlab"
sources = ['src/codnexlab']
requires = ['plotly==5.17.0'
]

[tool.briefcase.app.codnexlab.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.codnexlab.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.codnexlab.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.codnexlab.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.codnexlab.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.codnexlab.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0',
    'plotly==5.17.0'
]

[tool.briefcase.app.codnexlab.android]
requires = [
    'toga-android>=0.3.0.dev34',
    'plotly==5.17.0'
]

### Environment

- Operating System: Windows
- Python version: 3.7.15
- Software versions:
  - Briefcase: 0.3.9

### Logs

[briefcase.2023_09_25-15_27_55.run.log](https://github.com/beeware/briefcase/files/12719405/briefcase.2023_09_25-15_27_55.run.log)

**Comment by rmartin16** [comment]
> I am still receiving a message saying the module cannot be found.

The Briefcase commands will default to the output format for the host machine if one is not explicitly specified. Since you're running Windows, the `briefcase update -r` command is the same as the `briefcase update windows app -r` command. Therefore, use `briefcase update android -r` to update the build for an Android app output format. Alternatively, you can install new requirements and run the Android app with `briefcase run android -r`.

> I got an error at the end of running the --log stating the 'Android emulator was unable to start!' 

The output from the Android emulator suggests your machine does not have hardware acceleration enabled.

```
           ERROR   | x86_64 emulation currently requires hardware acceleration!                                                                                  android_sdk.py:1086
           CPU acceleration status: HAXM is not installed on this machine                                                                                        android_sdk.py:1086
           More info on configuring VM acceleration on Windows:                                                                                                  android_sdk.py:1086
           https://developer.android.com/studio/run/emulator-acceleration#vm-windows                                                                             android_sdk.py:1086
           General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.                                                  android_sdk.py:1086
```
This will need to be resolved to run the emulator. Alternatively, you can connect a physical Android device in debugging mode and run the app there.

> I did not have an android file in my folder until I ran the log. is it okay to delete the android file that was created?

You can; however, that is where Briefcase caches the build for the app. So, if you delete it, it will need to be created all over again.

Furthermore, though, you are using Python 3.7 which is limiting your version of Briefcase to 0.3.9. Both of these versions are quite old. I recommend you install at least Python 3.8 and use that for your development with Briefcase.

**Comment by rmartin16** [comment]
Feel free to ask more questions in our [Discord](https://beeware.org/bee/chat/) or in the [Discussions](https://github.com/beeware/briefcase/discussions) if you run in to additional issues.
