### ISSUE TITLE
The `-v` flag no longer prints debug output to the console

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1501]
### Describe the bug

When Briefcase is started with the `-v` flag, debug output is no longer printed to the console. Furthermore, when `-vv` is used, both debug and deep debug output is printed.

The log file, though, doesn't appear to be affected and continues to always include debug logging and the `-vv` flag still includes deep debug.

### Steps to reproduce

Run `briefcase build -v`.

### Expected behavior

When the `-v` is used, debug output should be printed to the console.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.13
- Software versions:
  - Briefcase: v0.3.16

**Comment by rmartin16** [comment]
It appears that 2d12dc4 redefined the debug logging level as deep debug.

```diff
class Log:
    """Manage logging output driven by verbosity flags."""

-    # level of verbosity when debug output is shown in the console
-    DEBUG = 1
-    # printed at the beginning of all debug output
+    # Level of verbosity when debug output is shown in the console
+    DEBUG = 2
+    # Printed at the beginning of all debug output
    DEBUG_PREFACE = ">>> "
    # subdirectory of command.base_path to store log files
    LOG_DIR = "logs"
```

**Comment by rmartin16** [comment]
tbh, I'm kinda mindblown that the entire test suite is apparently insensitive to `briefcase.console.Log.DEBUG` being changed.

But it seems that when we changed the debug level from `2` to `1` in 4cdbc9f a while back when we added debug output for third party tools....we didn't also update the tests checking _only_ for debug output, e.g. [test_debug_call()](https://github.com/beeware/briefcase/blob/main/tests/integrations/subprocess/test_Subprocess__check_output.py#L130).

**Comment by freakboy3742** [comment]
I don't think it's entirely surprising that a change to DEBUG didn't trigger anything in the tests; log output isn't generally asserted in tests unless either the output is the point, or output is the only signal that something has been done.

However, there's definitely some unintended damage from the DEBUG=1->2 change.

For me, I think the underlying issue is that we've got multiple competing terminology and descriptions of debug level - there's the call we use to do the debug (logger.info, logger.debug etc), and the constant that describes log level. We've also got DEBUG_PREFIX, which is really a "subprocess prefix" rather than anything related to debug.

My inclination is that rather than having `if verbosity >=` calls in the general codebase, verbosity should be checked exactly once, and we should be using the appropriate `logger` call. That likely means adding a `logger.deep_debug` that is only used by subprocess and selected "way-too-much-detail" logging options (I can't think of any in particular candidates, but at least conceptually it's not *explicitly* a subprocess feature).
