### ISSUE TITLE
App store submission : During review, your app installed or launched executable code, which is not permitted on the App Store

### ISSUE THREAD

**Issue by albrownwood** [beeware/briefcase#1655]
### Describe the bug

Getting this message when submitting app created with briefcase on app store.

```
Guideline 2.5.2 - Performance - Software Requirements
During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.
Please note that while educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code, such code may not be used for other purposes and such apps must make the source code completely viewable and editable by the user.
```

### Steps to reproduce

1. briefcase package macOS Xcode
2. use Xcode the sign and notarize the app
3. use Xcode to upload to app store connect for review
4. submit app for review
5. app review fails as described

### Expected behavior

Expectation is to be able to submit an app created with briefcase on the app store.
Is this problem solvable or does it mean that app embedding a python interpreter are simply not allowed on the app store?

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
I'm not sure what you expect us to do here.

You've provided *literally* no information to work on, other than the rejection message returned from the App Store. 

Even the *platform* that you're targeting is, at best, implied. Despite an explicit prompt to provide operating system and software version detail, the only hint that this is likely a macOS packaging issue is the first line of your reproduction instructions.

Ultimately - you've told us nothing about the app that you're packaging, so we have no way to know if the issue is your app, or something that Briefcase is doing.

Based on the App Store rejection message, it sounds like the packaged app contains executables. These are likely installed by one of your dependencies. However, as you haven't told us anything about your app's dependencies, we have no way to tell.

If you want to provide more (which is to say - *any*) detail about what you're doing, we might be able to help.

**Comment by albrownwood** [comment]
Hello, I wanted to confirm first there is no well known restriction related to submitting an app made with briefcase and the appstore. The app in question has only 2 dependences: wxPython, asn1tools and it does not contain any extra executable, the app shows a UI using wx and allows the user perform some data manipulations.

Operating System: Sonoma 14.3.1
Python version: 3.12
Briefcase: 7682008b8a1357cbb83e6ff97cfb7cfce1f2f51c

**Comment by freakboy3742** [comment]
Are you *sure* it doesn't contain any extra executables? Have you audited the full contents of the wxPython and asn1tools package (and *all* the dependencies of those packages) to see if there's an executable file? It's extremely common for Python packages to include utility binaries.

**Comment by albrownwood** [comment]
I audited all the dependencies and indeed I found some binary utilities in there! Will update here when I get the results of submission.

**Comment by freakboy3742** [comment]
FYI - in terms of automation, you may find the [`cleanup_paths`](https://briefcase.readthedocs.io/en/stable/reference/configuration.html#cleanup-paths) configuration option helpful. This allows you to specify files that are installed as part of your dependencies (or any other part of the Briefcase creation process) that you want to be purged before packaging is complete. This can be useful for removing parts of the standard library or dependencies that you don't want or need at runtime.
