### ISSUE TITLE
Installing .apk fails on device

### ISSUE THREAD

**Issue by AndiLeni** [beeware/briefcase#1698]
### Describe the bug

Hello,

I tried compiling my app to a release .apk file with `briefcase package android -p apk`.
When I try to install this apk on my android 12 phone, the package installation fails with `App Not Installed as Package Appears to Be Invalid`

### Steps to reproduce
-/-

### Expected behavior

The generated apk should be distributable.

### Environment

- Operating System: Windows 10
- Python version: 3.11.5
- Software versions:
  - Briefcase: 0.3.17
  - Toga: 0.4.2

### Logs

None visible on phone.

**Comment by freakboy3742** [comment]
Thanks for the report - the issue is code signing. The APK (or AAB) produced by `briefcase package android` isn't signed; you need to [manually sign the binary](https://briefcase.readthedocs.io/en/stable/how-to/publishing/android.html) to use it on your device. 

The Android docs don't explicitly mention this requirement - I've opened #1703 to address this gap in the documentation.

**Comment by AndiLeni** [comment]
Oh I see. Thanks for the quick response!
