### ISSUE TITLE
Dragging app window from Stage Manager to Desktop in Dev Mode prompts warning in Terminal

### ISSUE THREAD

**Issue by ashleyplusplus** [beeware/briefcase#1806]
### Describe the bug

Dragging the open app window from Mac Stage Manager to Desktop in Developer Mode results in this warning populating in terminal

### Steps to reproduce

1. Run the command `briefcase dev` in Terminal.
2. Drag application window from Stage Manager to Desktop.
3. See warning `2024-05-20 10:53:09.125 Python[19914:2661703] Warning: Window move completed without beginning`

### Expected behavior

Nothing

### Screenshots

<img width="682" alt="image" src="https://github.com/beeware/briefcase/assets/57259724/d1ce0d35-28e6-4858-8469-5da23737ffac">

### Environment

- Operating System: macOS Sonoma 14.5
- Python version: 3.12.1
- Software versions:
  - Briefcase: 0.3.18
  - Toga: 0.4.4

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. This appears to be a Cocoa system message, rather than anything Toga or Briefcase is generating. It won't be visible at runtime (it's only visible here because dev mode is exposing the system log). It's not unheard of for macOS apps to generate system log messages because of bugs in Cocoa itself. On that basis, I think we can close this as "can't fix".
