### ISSUE TITLE
Could not determine java version from '11.0.1'.

### ISSUE THREAD

**Issue by RenaKunisaki** [beeware/briefcase#183]
Building Android tutorial fails on Arch x64:

```
rena@gabumon:…/android/hello-beeware/hello> python setup.py android -s
running android

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-android==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/38/b0/fbb7c46d6a40d374ba68d6984de36fbe313a111809209b774a56d8868030/toga_android-0.3.0.dev11-py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-android==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-android==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: travertino, toga-core, toga-android
Successfully installed toga-android-0.3.0.dev11 toga-core-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /home/rena/projects/android/hello-beeware/hello
Installing collected packages: hello
  Running setup.py install for hello ... done
Successfully installed hello-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.

Starting Hello
Downloading https://services.gradle.org/distributions/gradle-3.4-bin.zip
...................................................................................................................................................................
Unzipping /home/rena/.gradle/wrapper/dists/gradle-3.4-bin/aeufj4znodijbvwfbsq3044r0/gradle-3.4-bin.zip to /home/rena/.gradle/wrapper/dists/gradle-3.4-bin/aeufj4znodijbvwfbsq3044r0
Set executable permissions for: /home/rena/.gradle/wrapper/dists/gradle-3.4-bin/aeufj4znodijbvwfbsq3044r0/gradle-3.4/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.1'.
```

**Comment by freakboy3742** [comment]
The Android build system is known to be broken at the moment - but that is a different error to the one we're used to seeing. Out of interest - what version/distribution of Java are you using? 11.0.1 isn't a version string that I'd expect to see from and Java interpreter/compiler that I've seen.

**Comment by RenaKunisaki** [comment]
```
$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13)
OpenJDK 64-Bit Server VM (build 11.0.1+13, mixed mode)
```

**Comment by freakboy3742** [comment]
Thanks for that detail. I can almost predict what the problem will be - someone has hard coded a regular expression to match a version number.

However, on investigation, it looks like this isn't a bug in our code - it's a bug in the Android build system. The error is being reported by Gradle trying to compile your Android source code.

My first suggestion would be to make sure you've got the latest versions of the Android build tools installed - it seems like the sort of thing that would have been reported and fixed fairly quickly. Beyond that, I'm not sure I have any good suggestions - I'm not overly familiar with Android's build tooling (which is why there are lingering problems with Android in general for BeeWare).

**Comment by Goddard** [comment]
This error can be fixed by using a newer version of gradle.

If you want to do it after running the python setup command it should generate a folder "android/gradle/wrapper/"

Inside that folder is a gradle-wrapper.properties file.  Change the line that searches for the gradle zip file.  Mine was 4.7, I changed it to 5 because 5 has support for openjdk 11. 

My build still failed after that, but at least I got past this issue.

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
