### ISSUE TITLE
Icon path specified in pyproject.toml is not recognized when building Xcode format

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [beeware/briefcase#1838]
### Describe the bug

Building `macos app` and building `macos Xcode` cannot recognize the same icon path - `macos app` uses the specified icons without issue whereas `macos Xcode` does not.

### Steps to reproduce

Run `briefcase build macos app --update-resources` and `briefcase build macos Xcode --update-resources` in project with an icons configuration.

### Expected behavior

`Xcode` and `app` shouldn't require separate icons configurations.

### Environment

- Operating System: macos 13.6.4
- Python version: Python 3.12.3
- Software versions:
  - Briefcase: 0.3.19.dev72+g83ece679

### Logs

Building `macos app`:
```
$ briefcase build macos app --update-resources

[my_briefcase_app] Updating application code...
Installing src/my_briefcase_app... done

[my_briefcase_app] Updating application resources...
Installing assets/icons/my_briefcase_app/AppIcon.icns as application icon... done

[my_briefcase_app] Removing unneeded app content...
Removing unneeded app bundle content... done

[my_briefcase_app] Application updated.

[my_briefcase_app] Building App...

[my_briefcase_app] Ad-hoc signing app...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 00:02

[my_briefcase_app] Built build/my_briefcase_app/macos/app/my_briefcase_app Server.app
```

Building `macos Xcode`:
```
$ briefcase build macos Xcode --update-resources

[my_briefcase_app] Updating application code...
Installing src/my_briefcase_app... done

[my_briefcase_app] Updating application resources...
Unable to find assets/icons/my_briefcase_app/AppIcon-16.png for 16px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-32.png for 32px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-64.png for 64px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-128.png for 128px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-256.png for 256px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-512.png for 512px application icon; using default
Unable to find assets/icons/my_briefcase_app/AppIcon-1024.png for 1024px application icon; using default

[my_briefcase_app] Removing unneeded app content...
Removing unneeded app bundle content... done

[my_briefcase_app] Application updated.

[my_briefcase_app] Building Xcode project...
Build succeeded.
Building... done

[my_briefcase_app] Built build/my_briefcase_app/macos/xcode/build/Release/my_briefcase_app Server.app
```

**Comment by freakboy3742** [comment]
Thanks for the report; however, this is operating as intended and documented ([app](https://briefcase.readthedocs.io/en/stable/reference/platforms/macOS/app.html#icon-format); [Xcode](https://briefcase.readthedocs.io/en/stable/reference/platforms/macOS/xcode.html#icon-format)). This is because the Xcode template involves compiling the final icon from source, whereas the app template relies on the user providing a pre-compiled icon. As an end-user won't normally need to use *both* the app and Xcode template for a given project, I don't consider the different format requirements to be a significant imposition.

There is a long-standing feature request (#386) to be able to minimise the number of supplied icons by providing a single high-resolution image and backfill the remaining icons from that single starting point; if this were to be implemented, the inconsistencies between the two platforms would become less significant.

**Comment by michelcrypt4d4mus** [comment]
cool. as a suggestion then i would link from [this part of the documentation](https://briefcase.readthedocs.io/en/stable/reference/configuration.html#icon) which is what i was reading as a new user to the links you provided. as a new user i have been reading a lot of the documentation and i never found those sections.
