### ISSUE TITLE
[ios]Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.

### ISSUE THREAD

**Issue by voicers** [beeware/briefcase#184]
Failed to load the app , gives error as : 

2019-01-10 14:56:47.345317+0800 trialPybee[11551:4381103] Initializing Python runtime...
2019-01-10 14:56:47.420197+0800 trialPybee[11551:4381103] Installing Python NSLog handler...
2019-01-10 14:56:47.566467+0800 trialPybee[11551:4381103] Running '/var/containers/Bundle/Application/AA955D1D-F552-4D99-BBC9-A346BE39EEAD/trialPybee.app/Library/Application Support/pybee.trial.trialPybee/app/trialPybee/__main__.py'...
2019-01-10 14:56:47.825096+0800 trialPybee[11551:4381103] *** Assertion failure in void _UIApplicationMainPreparations(int, char **, NSString *__strong, NSString *__strong)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.94.10/UIApplication.m:4306
2019-01-10 14:56:47.825187+0800 trialPybee[11551:4381103] Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.
2019-01-10 14:56:47.832553+0800 trialPybee[11551:4381103] Leaving...

I've  tried to fix the problem by changing (line 122,main.m)"UIApplicationMain(argc, argv, nil, @"PythonAppDelegate")" to "UIApplicationMain(argc, argv, nil, @"Pyobjus")", however failed ,and gived error as "No class named Pyobjus is loaded."

**Comment by voicers** [comment]
@freakboy3742 
I wasn't using kivy , mate. I was just following this tutorial   https://briefcase.readthedocs.io/en/latest/background/getting-started.html.

And the __init.py__ is the initial script  provided by "cookiecutter https://github.com/pybee/briefcase-template".

**Comment by freakboy3742** [comment]
Firstly, I'll point out that your tone is not helpful. Your report didn't description *anything* about what you were doing. You just provided a stack trace. If you want help, you have to help us to help you.

Secondly: assuming you haven't done anything else other than *literally* what is in that tutorial, then you've got exactly the result you'd expect to see. You haven't specified an application; and so at runtime, the iOS version of the application crashes, with an error indicating that it can't find an application to run. You'll get an analogous result on any other platform - although it will manifest in different ways (e.g., an application starting, but not displaying a window; or starting but crashing immediately). 

Admittedly, the Briefcase tutorial isn't especially illuminating in that regard. It's really a "how to use the tool when you've already got something to package" tutorial, rather than a "how to start from scratch and get some output". That could definitely be spelled out better in that tutorial.

If you *have* done provided some sort of application logic (which I'm guessing you have done, since you reported exactly the same bug on the Toga repository), then if you want us to help you, *you have to tell us what you've done*. My powers of mind reading are deceptively poor.

**Comment by shirakaba** [comment]
For anyone else running into this, here's a bit of boilerplate to get a UIKit GUI initialised:

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/73895515-f8ba-4071-a841-76c7c17fd34d">

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/b31ae6e1-9383-415b-9689-1ce6f6181d57">


```h
// PythonAppDelegate.h
#import <UIKit/UIKit.h>

@interface PythonAppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow *window;

@end
```

```objc
#import "PythonAppDelegate.h"

@interface PythonAppDelegate ()

@end

@implementation PythonAppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    
    // Create a view controller
    UIViewController *viewController = [[UIViewController alloc] init];
    viewController.view.backgroundColor = [UIColor whiteColor];
    
    // Create a label
    UILabel *label = [[UILabel alloc] initWithFrame:self.window.bounds];
    label.text = @"Hello, World!";
    label.textAlignment = NSTextAlignmentCenter;
    label.font = [UIFont systemFontOfSize:24.0];
    
    [viewController.view addSubview:label];
    
    self.window.rootViewController = viewController;
    [self.window makeKeyAndVisible];
    
    return YES;
}

@end
```

I've still got to work out how to call our Python instance from that context, but at least it's one step further.

**Comment by freakboy3742** [comment]
> For anyone else running into this, here's a bit of boilerplate to get a UIKit GUI initialised. 
...
> I've still got to work out how to call our Python instance from that context, but at least it's one step further.

FWIW - what you've done here definitely defines a class called PythonAppDelegate, which is what needs to exist... but it's not a Python AppDelegate - it doesn't do anything *with* Python. It just has the required name.

If you've used Briefcase to get the rest of your project stub going, then the process will have a Python interpreter defined in the context of the main method; you won't be able to call that interpreter from anywhere unless you explicitly pass around a reference to that Python interpreter (e.g., adding it as a property of your PythonAppDelegate). 

Once you've got that reference, you're essentially using Python's embedded C API to control the Python interpreter - the same API you'd use two write a binary module in C, but coming at the problem from the other direction (i.e., instead of Python calling your code, you're calling Python). The main method contains some examples of invoking a file (first `nslog`, and then `__main__.py`; but the full C API is at your disposal.

**Comment by shirakaba** [comment]
I see, thanks! I think in my case I'd misunderstood what to expect from the Briefcase templates. It's clear now that even in the "no UI framework" template, it's Python puppeteering the UIKit app rather than the other way around. In my case I actually have a UIKit app which I want to call a headless Python script from. The value I saw in the Briefcase templates was that they'd handle a bunch of project setup like the Xcode build phase scripts and some support for installing `pypi` packages, but perhaps if I want to call Python from a standard UIKit app, then just directly following the Python embedder API is the easier path to achieve that. Is there a CocoaPod or something that sets up a standard UIKit project for calling Python?

**Comment by freakboy3742** [comment]
I'm not aware of a CocoaPod or similar; I know [PythonKit](https://github.com/pvieito/PythonKit) exists, but I've never really tried to use it myself, so I can't really comment on how to use it. 

Briefcase is very much targeted at the "Your app is a Python app that needs to call UIKit" use case, which is why the code is structured the way it is. If you're got a UIKit application that needs to call Python, the overall structure won't be *that* much different, though. The major difference is that the "run the app" part of the Briefcase-generated main method (everything after [this line](https://github.com/beeware/briefcase-iOS-Xcode-template/blob/main/%7B%7B%20cookiecutter.format%20%7D%7D/%7B%7B%20cookiecutter.class_name%20%7D%7D/main.m#L192) can be replaced with whatever "normal iOS app" AppDelegate handling you want to have. Most of the rest of the main method is the "instantiate a Python interpreter" code; that *could* be moved into the startup lifecycle of your AppDelegate if you wanted to; or it can be left where it is, and you can set an attribute on your delegate object as I previously indicated. 

Beyond that, it's up to you how and when you invoke Python code. The code in the mainline method shows how you can use the C API to retrieve a specific module and invoke that module as `main`; but you could use the same API to extract a single function from a module and invoke it, if you wanted, or do anything else that you could do in Python.

If you want to use Briefcase to manage an "iOS app that calls Python" app, you're going to hit a little bit of friction, because Briefcase assumes that anything in the Xcode project can be deleted and replaced by re-generating the template. In general, you shouldn't need to commit the contents of your build folder to version control; but in your case, you will need to, because that's where your actual app code will be. You'll also want to be careful about re-running `briefcase create iOS`; this is sometimes necessary when you change some properties in your app (like version numbers), but it won't be an easy option for you, because re-running briefcase create will delete your app code in favor of a freshly generated template.

**Comment by shirakaba** [comment]
PythonKit did catch my eye, though it looks like it's geared towards simply running pure Python scripts and doesn't think as far as PyPi modules and wheels, so didn't meet my use-case.

> The major difference is that the "run the app" part of the Briefcase-generated main method (everything after [this line](https://github.com/beeware/briefcase-iOS-Xcode-template/blob/main/%7B%7B%20cookiecutter.format%20%7D%7D/%7B%7B%20cookiecutter.class_name%20%7D%7D/main.m#L192) can be replaced with whatever "normal iOS app" AppDelegate handling you want to have.

Thanks, I was thinking of picking apart `main.m`, and wasn't totally sure which bits it would make sense to cut out for my case. This will help.

> If you want to use Briefcase to manage an "iOS app that calls Python" app, you're going to hit a little bit of friction, because Briefcase assumes that anything in the Xcode project can be deleted and replaced by re-generating the template.

Understood! I'm familiar with this kind of workflow from NativeScript and Expo (who coined the term [Continuous Native Generation](https://docs.expo.dev/workflow/continuous-native-generation/) for it).

Thanks for confirming that Briefcase is maybe a bad fit for my use-case. I think I can study useful stuff from the template, and just having the `.xcframework` is a great step forwards, but I'll probably need to look at the Python iOS embedding [docs](https://docs.python.org/3.13/using/ios.html) from here.

The bit that's really stumping me is how to use a third-party library, [pycryptodome](https://pypi.org/project/pycryptodome/). I actually tried seeing how Briefcase handles it by adding `requires = ["pycryptodome>=3.20.0"]` to my `pyproject.toml` and running `briefcase dev` and `briefcase build iOS`, but I couldn't see any evidence of it having made any changes to the project at all.

**Comment by freakboy3742** [comment]
> Thanks for confirming that Briefcase is maybe a bad fit for my use-case. I think I can study useful stuff from the template, and just having the `.xcframework` is a great step forwards, but I'll probably need to look at the Python iOS embedding [docs](https://docs.python.org/3.13/using/ios.html) from here.

Those docs are essentially just the documented version of what Briefcase has embedded in a template; so yes - you can absolutely "roll your own from scratch" if you want. 

The only part those docs don't cover is how to install dependencies from pip. As pip doesn't currently recognise iOS as a platform, you currently have to do a little bit of wrangling to install dependencies. Briefcase manages that process - and if you want to see what Briefcase is doing, you can pass `-vv` to any Briefcase command to see the underlying commands that have been executed. Replicate those commands in your own shell, and you should be able to replicate what Briefcase is doing.
 
> The bit that's really stumping me is how to use a third-party library, [pycryptodome](https://pypi.org/project/pycryptodome/). I actually tried seeing how Briefcase handles it by adding `requires = ["pycryptodome>=3.20.0"]` to my `pyproject.toml` and running `briefcase dev` and `briefcase build iOS`, but I couldn't see any evidence of it having made any changes to the project at all.

Just adding the requires to an existing project won't do anything by itself - you also need to call `briefcase update -r` to force an update of requirements. 

However, in terms of pycrytodome specifically - that is a package with a binary component, so you'll also need to manage compiling the binary wheels, and putting them somewhere you can install them, as PyPI won't accept iOS uploads. The [Mobile Forge](https://github.com/beeware/mobile-forge) project exists to manage that compilation process for some common wheels, but we don't currently have a recipe for pycryptodome. Mobile forge is also currently in a slightly broken state as I'm in the process of incorporating the 3.13 patches back into the ecosystem - those fixes should be in place in a couple of days.
