### ISSUE TITLE
AppImages running PySide6>=6.6.2 immediately seg fault

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1908]
### Describe the bug

Discovered in https://github.com/beeware/.github/pull/135 via its [CI testing](https://github.com/beeware/.github/actions/runs/9877526660/job/27280641765?pr=135), AppImages using PySide6>=6.6.2 will immediately seg fault at runtime.

```
[pysidetest] Starting app...
===========================================================================
Fatal Python error: Segmentation fault

Current thread 0x000075892c316740 (most recent call first):
  File "/tmp/.mount_pysideNVUqtZ/usr/app/pysidetest/app.py", line 38 in main
  File "/tmp/.mount_pysideNVUqtZ/usr/app/pysidetest/__main__.py", line 5 in <module>
  File "/tmp/.mount_pysideNVUqtZ/usr/python/lib/python3.10/runpy.py", line 86 in _run_code
  File "/tmp/.mount_pysideNVUqtZ/usr/python/lib/python3.10/runpy.py", line 96 in _run_module_code
  File "/tmp/.mount_pysideNVUqtZ/usr/python/lib/python3.10/runpy.py", line 224 in run_module
  File "<string>", line 1 in <module>

Extension modules: xxsubtype, shiboken6.Shiboken, PySide6.QtCore, PySide6.QtGui, PySide6.QtWidgets (total: 5)
/tmp/.mount_pysideNVUqtZ/AppRun: line 11: 792928 Segmentation fault      (core dumped) "${APPDIR}/usr/python/bin/python3" -u -s -X utf8 -c "import runpy, sys; sys.path.pop(0); runpy.run_module('${BRIEFCASE_MAIN_MODULE}', run_name='__main__', alter_sys=True)" "$@"
```

### Steps to reproduce

```bash
briefcase new \
    -Q formal_name=pysidetesting \
    -Q bootstrap=PySide6 \
    --no-input && \
cd pysidetesting && \
briefcase run linux appimage
```

### Expected behavior

AppImages using PySide6 does not crash.

### Environment

- Operating System: pop os 22.04
- Python version: 3.12.2, 3.10.14
- Software versions:
  - Briefcase: `0.3.20.dev22+g93fd04b5`

### Logs

[briefcase.2024_07_10-13_39_46.run.log](https://github.com/user-attachments/files/16167011/briefcase.2024_07_10-13_39_46.run.log)

**Comment by freakboy3742** [comment]
My enthusiasm for chasing this down is essentially zero. Briefcase's AppImage support is deprecated in all but name at this point; I'm entirely comfortable fixing this by disabling AppImage testing for PySide.

**Comment by andreasgriffin** [comment]
With PyQt6 and AppImage I also get seg fault.
It would be great, if Briefcase could support AppImage again.  It is a very popular format.

**Comment by freakboy3742** [comment]
As far as we're aware, the issue with AppImage has nothing to do with Briefcase - it's entirely an issue with the [linuxdeploy Qt plugin](https://github.com/linuxdeploy/linuxdeploy-plugin-qt). Any issues should be reported upstream.

Unfortunately, we've had to take AppImage support out of our CI tested configurations because we've found it to be wildly inconsistent in stability, subject to a [large number of issues in the compatibility of binary packages](https://briefcase.readthedocs.io/en/stable/reference/platforms/linux/appimage.html#runtime-issues-with-appimages), and [fundamentally incapable of deploying some apps](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/42). 

In its current state, it is very difficult for us to recommend the use of AppImage as a deployment format.
