### ISSUE TITLE
Can onefile build mode be supported

### ISSUE THREAD

**Issue by CodyGit** [beeware/briefcase#1919]
### What is the problem or limitation you are having?

When I update the software version, users need to repeat the installation, which is very troublesome for them. Users hope to use it after downloading.

### Describe the solution you'd like

PyInstaller can build all file into one with mode --onefile, I hope **briefcase** can also have similar functions

### Describe alternatives you've considered

PyInstaller can build all file into one with mode --onefile, I hope **briefcase** can also have similar functions

**Comment by freakboy3742** [comment]
Briefcase doesn't support a "single file" distribution mode, and this is a deliberate design decision.

Making "single file" distribution mode work requires fairly invasive customisation of Python's import system. These customizations make single file mode *possible*, but it is rarely *reliable*. Python code, fundamentally, expects to be executed as an interpreter running over a collection of files on disk. When this isn't the case, the failure mode usually isn't obvious, and is almost impossible for an app developer to fix.

If you don't believe me - this is why the (now deprecated) [`zip_safe`](https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html) option existed in setuptools. `zip_safe` was an essential part of the packaging ecosystem when Python code was packaged as "eggs". The wheel format replaced eggs... and along with it, also removed the "feature" of eggs that required the feature - eggs (in theory) allowed code to be run from the egg without unpacking the egg. It wasn't ported to wheels as a feature because this mode of execution simply wasn't reliable in general.

Single file distribution fundamentally isn't required, either - as long as there's single file *distribution*. Briefcase does this, and can be used for both command line and GUI apps.

As a result - closing this WONTFIX.

**Comment by CodyGit** [comment]
@freakboy3742 Thanks for your reply
