### ISSUE TITLE
How does briefcase work with a private package index?

### ISSUE THREAD

**Issue by thisisnaty** [beeware/briefcase#192]
I'm trying to consume a package from an index different to pypi and have it installed to /app_packages once my project gets packaged by briefcase. I noticed that briefcase runs "pip install --upgrade" for all install_requires. So how can I make sure it gets my package from my private feed?

**Comment by freakboy3742** [comment]
At present, we don't support private PyPI repositories. However, it definitely sounds like a worthwhile feature. If you wanted to add a flag to the base task definitions that allowed you to specify a custom PyPI repository (in the same way that we allow customizing the application template or support package) we'd gladly add that feature.

**Comment by mofe23** [comment]
Hi,
I had to use some private packages, and ended up in using `pipyserver` to serve my private packages and edit pip and distutils config to use it. 
As i got this to work without any problems i dont see a need to implement this functionality in briefcase tbh.
@thisisnaty guess this should also work if you configure pip and distutils to use your private index instead of the local pypiserver.

```
pip install pipyserver passlib
htpasswd -sc htpasswd.txt my_user
mkdir packages
pypi-server -p 8080 -P htpasswd.txt packages
```

`vim ~/.pip/pip.conf`
```
[global]
extra-index-url = http://localhost:8080/simple/
```

`vim ~/.pypirc`
```
[distutils]
index-servers =
  pypi
  local

[pypi]
username:<your_pypi_username>
password:<your_pypi_passwd>

[local]
repository: http://localhost:8080
username: my_user
password: my_password
```

After that, i was able to push an sdist to my local index using `python setup.py sdist upload -r local`

My Briefcase config for OSX looks like this, and `nfcpy` and `nfctlog-python` are installed from private index.

```
...
        'macos': {
            'app_requires': [
                'toga-cocoa==0.3.0.dev11',
                "hexdump",
                "appdirs",
                "nfcpy",
                "nfctlog-python"
            ]
        },
...
```

**Comment by freakboy3742** [comment]
@mofe23 Thanks for those details. This is definitely an edge case, but also one worth formally documenting. If anyone wanted to turn this into a HOWTO page in briefcase's docs...

**Comment by mofe23** [comment]
@freakboy3742  #242
