### ISSUE TITLE
if NPM not installed > throws unrelated exception

### ISSUE THREAD

**Issue by academay** [beeware/briefcase#196]
I didn't have NPM installed on my Windows 7 machine. So this command:

    python setup.py django -s

resulted in a cryptic exception trace (from 'subprocess' module);

I figured out that:

 - i didn't have NPM installed
 - in /briefcase/django.py:72    shutil.which("npm") returns None
 - the output is fed directly to subprocess

I suggest to check the return value of "which( )",  and give a better **useful error message**.

Here's what I had in mind:

        cmd_parts = [shutil.which("npm"), "install"]
        if not all(cmd_parts):
            print('oh no, npm is either not installed, or not found in the PATH')
            if os.platform=='win32':
                print('https://nodejs.org/en/')
                exit(1)
            else:
                ??? apt install npm ???
        selfdir = os.path.abspath(self.dir)
        subprocess.Popen( cmd_parts, cwd=selfdir ).wait()

**Comment by freakboy3742** [comment]
We've temporarily disabled our Django backend due to the limitations in using the 0.3 branch of Toga. Closing this ticket until we're able to re-add web support.

However, on a related note: the 0.3 development version of Briefcase includes much stronger checks for system dependencies; so, when the Django/web backend is re-introduced, we'll be in a much better position to verify these sorts of details.
