### ISSUE TITLE
module "environ" not found? Where should it come from? 

### ISSUE THREAD

**Issue by academay** [beeware/briefcase#197]
running briefcase as part of pybee;  

    python setup.py django -s

shows this error:
  File "D:\temp\eight\django\briefcase\settings\base.py", line 23, in <module>
    environ.Env.read_env()
AttributeError: module 'environ' has no attribute 'Env'

I tried innocently to

    pip install environment

but got something completely different ;) another module with the same name:

      File "D:\temp\eight\django\briefcase\settings\base.py", line 23, in <module>
        environ.Env.read_env()
    AttributeError: module 'environ' has no attribute 'Env'

I guess it's should've been part of another package, but I wouldn't don't which or what.

this is my settings:

1. all freshly installed yesterday 2019-03-08
1. windows 7 x64
1. python 3.6
1. pybee runs well otherwise, and builds 'windows' without a problem.

**Comment by freakboy3742** [comment]
Hrm - that's odd.

For the record, the dependency required here is "django-environ". However, it *should* have been installed when toga-django was installed, as it's listed as a dependency of that package in `installed_packages` for toga-django.  

Can you please remove the `django` directory for your project, and provide the full log history when you ran `python setup.py django -s`?

**Comment by jess010** [comment]
I'm experiencing an issue which may be related to this. When I attempt to build a django app with briefcase tutorial for single page web app Farenheit to Celsius (https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-1.html), 

```python setup.py django -s```

I get the following error message:

```ModuleNotFoundError: No module named 'environ'```

See attached log.txt file including the detail following the successful installation of node modules. No other errors received before this.

I'm running Max OS 10.14.3 and Python 3.6.8. I'm also using a conda virtual environment instead of venv / virtualenv, but all packages except python its dependencies are installed through pip, so I would't think that this should be a factor, but including this info for sake of completeness.

[log.txt](https://github.com/beeware/briefcase/files/3149306/log.txt)

**Comment by mulka** [comment]
I also ran into this problem. I don't see installing toga-django mentioned in the briefcase tutorial... Where would that have been?

**Comment by mulka** [comment]
I'm using pipenv. Not sure if that matters.

**Comment by mulka** [comment]
Ok, looks like it doesn't matter, was able to reproduce with pip and a virtualenv. The first error you get is "ImportError: No module named 'django'" even though it looks like it tried to install django, maybe it is installing it somewhere else?

**Comment by jess010** [comment]
I had a go at using virtualenv instead of conda env to see if that made a difference - by using virtualenv, I was able to replicate the issue you had mulka with "ImportError: No Module named django". 

Whereas every time that I try with a virtual conda environment, the basic Django import seems to be fine, but I have the above import error with django-environ module per my comment above (despite the fact that installation of the module is successful). There does not appear to be an issue with any of the other modules.

I've tried Google, Stack Overflowing the environ error, and checking out GitHub issues for django-environ and cookiecutter, couldn't find any clues on this. Any ideas for further troubleshooting would be very much appreciated.

**Comment by freakboy3742** [comment]
We've temporarily disabled our Django backend due to the limitations in using the 0.3 branch of Toga. Closing this ticket until we're able to re-add web support.

**Comment by IT-chaser** [comment]
> running briefcase as part of pybee;
> 
> ```
> python setup.py django -s
> ```
> 
> shows this error:
> File "D:\temp\eight\django\briefcase\settings\base.py", line 23, in
> environ.Env.read_env()
> AttributeError: module 'environ' has no attribute 'Env'
> 
> I tried innocently to
> 
> ```
> pip install environment
> ```
> 
> but got something completely different ;) another module with the same name:
> 
> ```
>   File "D:\temp\eight\django\briefcase\settings\base.py", line 23, in <module>
>     environ.Env.read_env()
> AttributeError: module 'environ' has no attribute 'Env'
> ```
> 
> I guess it's should've been part of another package, but I wouldn't don't which or what.
> 
> this is my settings:
> 
> 1. all freshly installed yesterday 2019-03-08
> 2. windows 7 x64
> 3. python 3.6
> 4. pybee runs well otherwise, and builds 'windows' without a problem.

Maybe you can try to use pip3 instead of pip when installing django-environ
