### ISSUE TITLE
Cannot package `setuptools>=73.0.0` for universal builds for macOS

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1970]
### Describe the bug

The Aug 19 release of `setuptools==73.0.0` started including `dist-info` directories for the vendored packages. One of the vendored copies of `packaging` (since there's more than one...) does not contain a `WHEEL` file.

### Steps to reproduce

Add `setuptools==73.0.1` to `requires` and run `briefcase build` on macOS.

### Expected behavior

Seemingly malformed `dist-info` directories are ignored....or at least don't crash the build.

### Environment

- Operating System: Sonoma
- Python version: any
- Software versions:
  - Briefcase: `0.3.20.dev166+ge29943e7`

### Logs

https://gist.github.com/mribbons/1155fe873e6d7e5c46628767009b4ad4

**Comment by rmartin16** [comment]
I haven't fully taken in how this conversion process works for macOS....but I do wonder if including vendored packages is really intended. Quickly looking through it, it doesn't appear to have expected vendored packages to have `dist-info` directories.

**Comment by freakboy3742** [comment]
Oof... this is a weird one. 

I've logged this upstream as pypa/setuptools#4594; it's not clear if the inclusion of dist-info files was intentional, but if it was, the distutils-vendored version of packaging has incomplete data in (at least) the macOS wheel.

My immediate inclination is that the fix here is to restrict the search for binary packages to `dist-info` folders that are direct descendants of the install path, rather than a deep recursive search (so `*/*.dist-info`, rather than `**/*.dist-info`). The overall manifest for the top-level setuptools wheel includes all the files in the vendored packages, so that should give us all the information we need.
