### ISSUE TITLE
Make Finding the Windows Support Package Smarter

### ISSUE THREAD

**Issue by danyeaw** [beeware/briefcase#199]
Right now Briefcase just looks at the current installed Python version and blindly requests a url based on that: `https://www.python.org/ftp/python/%s/python-%s-embed-%s.zip`

Some versions of Python have no embedded package like Python 3.5 > 3.5.4 and other version like Python 3.7.2 have a post release version only (python-3.7.2.post1.embed-amd64.zip). If there is no embedded package at all, we can't really fix that, but we can report a useful error message. However, I do  think we should be able to support post and rc versions.

I think there is a few ways to solve this:
1. Directly link to each embedded version for each supported Python version. This requires upkeep as Python versions get updated.
1. Use requests to look whether the url is valid. Maybe we could pull all of the filenames from `https://www.python.org/ftp/python/%s`, use a regex to filter out non-embed ones, and then use the packaging or setuptools modules to do a version comparison to look for the latest release.

Any thoughts these two approaches, or other ideas for how we could handle this?

**Comment by freakboy3742** [comment]
I don't think we need to be overly smart here. If someone is looking for an embedded package for 3.5.5rc1, that means they've been able to install a *host* version of Python with that version; the fact that the embedded installer doesn't exist is something we can validate by the existence of the URL, and provide a nice error message.

If we wanted to be really nice, we could implement a fallback - this problem is really only going to exist for EOL releases - in that case, we could hardcode the path to the "last official" embedded installer, and warn the user that they're getting a *slightly* out of date Python that won't match their host environment (so, if they're using 3.5.5rc1 as the host, they'd get 3.5.4 in their installer). This "last official" link would only need to be updated every 18 months (when a version actually EOLs), and the "last official" versions are well announced in advance, so it should be entirely manageable.

**Comment by danyeaw** [comment]
> I don't think we need to be overly smart here. If someone is looking for an embedded package for 3.5.5rc1, that means they've been able to install a host version of Python with that version; the fact that the embedded installer doesn't exist is something we can validate by the existence of the URL, and provide a nice error message.

I agree with this, except for the case of the example with 3.7.2. There is no python-3.7.2.embed-amd64.zip only python-3.7.2.post1.embed-amd64.zip. I don't think a user would have 3.7.2.post1 installed on their computer, I think this is just that Python release team needed to repackage the embedded package a 2nd time. To handle that use case we could look for a post version if the version doesn't exist.

One other idea I had is that we could create a command line argument like --embed-version. Then if a user is using a version of Python that we can't find a version for, then they can override the version. Back to the use case above, if they were using Python 3.7.2, they could launch Briefcase with `python setup.py windows -b --embed-version 3.7.2.post1`. The user would have to investigate what versions do exist a bit, but that might be fine.

**Comment by freakboy3742** [comment]
Ah - right, I missed the significance of the `post1` tag - they're used if there's a problem identified with the originally packaged version. In those cases, the original 3.7.2 is taken down, and replaced by 3.7.2.post1. 

In this case, looking for `.postN` (for a couple of values of N) would make sense to me. So, it will look for python-3.7.2.embed-amd64.zip; if it can't find it, look for post releases that match the same pattern. If they're running 3.7.2 there will be *an* embed... it's just a matter of what it's called. That's essentially the same approach that's taken for b1/b2/b3 support packages that we host ourselves; the difference is that b1 may be *removed* when b2 is released.

There are three other possible approaches I can think of. 

First we hard code it for the few releases where this is a problem. -Post releases will be the exception, rather than the rule, so it shouldn't be *too* hard to stay ahead of this; however, it means we need to push a new release whenever a .post release is produced.

Second - we do the same thing, but we make the index describing where a -post release is needed something that is externally hosted.

Third, we take over hosting the support packages; we just copy the official ones, but we normalize the naming so that we can easily identify the "most recent" version - so 3.7.2 would be tagged as "b1", and 3.7.2-post1 would be "b2", following the naming convention used for other platforms.
