### ISSUE TITLE
[Winforms] `collections.abc.ABCMeta` is not available in Toga on `Winforms`

### ISSUE THREAD

**Issue by Mause** [beeware/briefcase#2067]
### Describe the bug

```
ERROR tests\hardware\test_location.py::test_current_location - ImportError: cannot import name 'abstractmethod' from 'collections.abc' (C:\Users\me\toga\testbed\build\testbed\windows\app\src\python311.zip\collections\abc.pyc)
```

### Steps to reproduce

Try to import `collections.abc.ABCMeta` on Winforms in the briefcase toga testbed

### Expected behavior

The import is successful

### Environment

- Operating System: Windows 10
- Python version: Python 3.11
- Software versions: 
  - Briefcase:  0.3.20
  - Toga: git main

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report.

It turns out that `ABCMeta` *isn't* technically part of `collections.abc`; it's `abc.ABCMeta`. It *is* importable as `collections.abc.ABCMeta` on Python3.13, as a result of some changes to how the collections.abc module is defined - but that effectively relies on an import side effect (the sort of thing that `__all__` exists to override)

So - the question then becomes "how did this manifest?" An error generated by `from collections.abc import ABCMeta` is correct - that's not where it should be imported from... but I can't find any instance of this in the existing code. How did this manifest in practice for you?

**Comment by mhsmith** [comment]
Specifically, this error happens on Python 3.12 but not Python 3.13:
```
% python3.12 -c 'from collections.abc import abstractmethod'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'abstractmethod' from 'collections.abc' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/collections/abc.py)
% python3.13 -c 'from collections.abc import abstractmethod'
%
```

But CI runs the testbed on Python 3.12, so if there was such an import, we should already have discovered it.

@Mause: I think you must have modified the code to add this invalid import. The fix is to change `collections.abc` to simply `abc`. 

If that's not the case, please explain what you did in more detail, and we'll reopen the issue.
