### ISSUE TITLE
Allow specifying an entry point

### ISSUE THREAD

**Issue by brechtm** [beeware/briefcase#22]
Currently, briefcase looks for app.py which starts the application. It would be nice if an entry point could be specified instead. See [pynsist](http://pynsist.readthedocs.io/en/latest/cfgfile.html)'s `entry_point` for inspiration.

**Comment by freakboy3742** [comment]
The 0.3 branch takes a different approach, expecting the app to be an runnable module (i.e., a module with a `__main__.py`. Since we're now adopting a Python standard for app execution, and it's possible to include multiple application modules in a project, the need for this feature should no longer exist.
