### ISSUE TITLE
Error while creating the Template (Android @ Linux - Ubuntu)

### ISSUE THREAD

**Issue by jcsantosx** [beeware/briefcase#23]
I'm a really newbie at this, so excuse me if I write something stupid :p

Moving on, the only error that appears is this:

> Complete output from command python setup.py egg_info:
>     running egg_info
>     error: Invalid distribution name or version syntax: toga--0.1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-klmvtchk-build/
> 

I looked in briefcase files, trying to figure it out where he requires the **toga--0.1** but can't find it, to help fixing this.

In the end it claims **Installation complete** ready to build the apk.
So, I ran the **ant debug** , 15 seconds later expels the *.apk with 135kb

I installed it on Android, no Bugs, except when I open it.
I says every time **Hello World** on a black screen, even if I don't used those words in any way (name, vars, config) so must be a default file that compiles...

Where to start to fixing this ?

Some suggestions:
I setup a new instance of Linux in VirtualBox for this, so I start **fresh**
The **pip install toga** was ok, but on **pip install briefcase** crashed with the **Exception git not installed** ,
and I easily installed git.
But the author intends that this tools should be used by children/newbies in this PyCon presentation, so I think we should create a file(for eack pybee package) like **os_requirements.py** or **os_setup.py** or even **os_must_have_this_to_run_this_tool.json**, and check if the OS requirements are installed (as soon we figure it out what we need in individual platform), for each platform (maybe it seems excessive, but is nice for those that are giving the first steps, and they don't go away to use another tool instead)

for this _git thing_ we can proceed with:

> has_git = subprocess.check_output(['git', '--version'])
> except FileNotFoundError:
> if os.uname()[0] == 'Linux' and 'Ubuntu' in os.uname()[3]:
> print ('you need to install git with "sudo apt-get install git"') right ?
> 

or maybe if the git is just to download the file and install it with pip, by simply change to **pip install --upgrade git+https://release** (it will always download the latest)

but I'm not sure if works with this command,
https://github.com/pybee/briefcase/blob/master/briefcase/app.py#L99
because I don't understand if is looking for _toga_ or something like _toga-android_ but for main packages works...

We could do this for git, JAVA_HOME, javac and so on, because even for me it's not easy to configure OS_dependencies.

Waiting for instructions, maybe I can help with this, with tousands of bugs :p

**Comment by eliasdorneles** [comment]
Hello @jcsantosx -- thanks for reporting and sorry for the delay on replying.

If I understood correctly, the problem you faced with the Android app was the `Hello World` text always showing up in the application, because it was probably hardcoded in the template. Could you try it again? The Android template got many updates over the last months, it's now [using modern Android tooling](https://github.com/pybee/Python-Android-template/pull/6) and Briefcase also got many improvements along the way.

About briefcase error reporting in general, this was one of the things that were worked on recently at Pycon sprints (see #36 and #37). It'd be awesome if you could try it again and give us your thoughts on what you find confusing and which things you think should be improved. But please open separate issues for each of these things, so we can keep track of them properly. :)

Right now I'm leaning to closing this issue because I believe the problems you mentioned (hardcoded `Hello World` and requiring `git` to pip install toga) are fixed by now, but I need to double-check that.

Thanks again for trying out BeeWare tools and sharing your experience!

**Comment by freakboy3742** [comment]
Given the age of this ticket, and the fact that the Android backed is about to undergo a radical change, I'm going to close this ticket. Thanks for the report!
