### ISSUE TITLE
Build falied with Android

### ISSUE THREAD

**Issue by JTorres258** [beeware/briefcase#244]
Hi,

I was trying to test BeeWare to develop some basic apps for Windows and Android. Following the tutorial, I was able to generate the .msi file for Windows and run it with no problem, but for Android I got this error:

```
Welcome to Gradle 4.7!

Here are the highlights of this release:
 - Incremental annotation processing
 - JDK 10 support
 - Grouped non-interactive console logs
 - Failed tests are re-run first for quicker feedback

For more details see https://docs.gradle.org/4.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.7/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
    $ adb logcat Python:* *:E

App started.
```

I've seen other issues regarding the generation of an Android app due to problems between VOC and Toga, but no one reports this kind of error. This similar post https://stackoverflow.com/questions/42754758/failure-build-failed-with-an-exception-ionic mentions that the problem is due to the OS (32-bit or 64-bit) but I am not really sure about it.  Any idea?

Thanks in advance.

**Comment by freakboy3742** [comment]
I can't say I've seen that particular error before - it looks like a fairly fundamental disconnect between Java and Gradle on your system. It's not even getting to the point where it's doing anything with BeeWare's code - it's failing in the process of just *starting* Gradle. 

The "32 vs 64 bit" thing at least seems *plausible* as a cause, but it's difficult to provide any further advice without having seen the bug myself. I suspect the next steps in debugging this will be related to a basic Gradle tutorial, rather than briefcase specifically - getting *any* project to build with Gradle, rather than the briefcase project specifically.

That said - I will also warn you that the Android backend is currently broken. Assuming you can get past this Gradle error, you're going to get "dex error in class file" error messages, and that will prevent you from getting an Android app running. That's a known problem, and unfortunately, the fix isn't simple. We're working on it, but progress is slow.

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
