### ISSUE TITLE
manually adding gradle build version

### ISSUE THREAD

**Issue by Goddard** [beeware/briefcase#247]
Not sure what is set to be done, but it would be great if we could set the gradle version to use if that is possible.

**Comment by freakboy3742** [comment]
I'm not sure how that would help. Gradle configurations are driven by the project itself, not the system - you don't "install gradle" and then ensure the right version of gradle is in use; each project downloads the version of gradle it requires. 

So... what exactly are you seeking to configure here?

**Comment by freakboy3742** [comment]
... and then I see your comment on #183. For future reference, providing links to other relevant tickets is exceedingly helpful for providing context. If there isn't an existing ticket, providing *all* the relevant context in a ticket is the next best thing.

In this case, the fix is to correct the gradle specification *for the android project*, not to allow overrides through the Briefcase interface.

Closing this issue on that basis.

**Comment by Goddard** [comment]
briefcase/cookie cutter is the template right?  It generates these files.

**Comment by freakboy3742** [comment]
No - briefcase uses cookiecutter over templates that are defined in other projects. [Python-Android-template](https://github.com/beeware/Python-Android-template) is the template that is used for Android projects.
