### ISSUE TITLE
HelloWorld app window does not appear. IOS build

### ISSUE THREAD

**Issue by AAAver** [beeware/briefcase#254]
After I followed all preparation steps in guide https://briefcase.readthedocs.io/en/latest/tutorial/getting-started.html , run python setup.py ios ( or python setup.py ios -s, I tried both) no pop-up screen with the app appeared. 
![image](https://user-images.githubusercontent.com/53422558/62067137-b1f5c780-b23b-11e9-8058-48b864e4f595.png) 
![image](https://user-images.githubusercontent.com/53422558/62067247-f08b8200-b23b-11e9-9af1-aba6ba426200.png)

I was thinking about that red line with toga core ERROR. I installed toga 11, but it didn't helped. After that I changed string 67 in setup.py from 'toga-ios==0.3.0.dev11' to 'toga-ios==0.3.0.dev12'
Error message disappeared but result was same 
![image](https://user-images.githubusercontent.com/53422558/62067499-9212d380-b23c-11e9-8ae7-a2d342c8a33b.png)
Non window with HelloWorld app.

I'm newbee here and I'm sorry if this issue looks stupid, but I tried to do a lot by myself before posting here.

**Comment by freakboy3742** [comment]
In all the examples you've provided here, you've invoked `python setup.py ios`. This will *create* an XCode project, but won't *run* it. To run the project you open the XCode project that has been created, and click on the "run" button.

If you pass in the `-s` option, that *should* start the project automatically. However, we're aware of a bug (#210) that prevents this from happening in some circumstances (usually if you've only installed XCode recently, or have only installed the iOS simulator recently). If you can provide a log of a `python setup.py ios -s` run, we can confirm if this is what is happening.

As an aside - thanks for providing the logs you have provided, but it's a lot easier to read logs if you paste them as *text*, rather than a screenshot. Github provides block markup (```) for exactly this purpose.

**Comment by AAAver** [comment]
I think in my case the root cause is much more trivial and is in that I don't have XCode and simulator installed. I didn't find these steps in the manual for Windows and thought everything is included in briefcase. So I have to fix it  first. Probably a virtual machine is the best solution, cause I'm not sure is it possible to run Xcode on Windows.

**Comment by freakboy3742** [comment]
Ah - right - that would definitely explain it.

Unfortunately, there's no way to build for iOS on Windows; just as there's no way to package a Windows app on macOS. These sort of platform limits are definitely something we should catch as an automated warning during the briefcase execution process.

**Comment by AAAver** [comment]
So, if I do all the procedures in windows, will I be able to launch the project in XCode in Mac virtual machine to test it? Or, I should pack everything using Mac?

**Comment by freakboy3742** [comment]
It's only the `-s` part (actually running the code) that requires XCode. You can generate the XCode code on any platform.

**Comment by AAAver** [comment]
Thanks a lot, You are very kind!

**Comment by freakboy3742** [comment]
Closing on the basis that this issue was resolved.

As an aside; the new version of briefcase does much more rigorous platform checks, and should report this problem before you get to the point of trying to run code.
