### ISSUE TITLE
Support for Poetry

### ISSUE THREAD

**Issue by jtrakk** [beeware/briefcase#262]
I've been falling in love with [Poetry](https://poetry.eustace.io) and I'd love to use briefcase on my Poetry apps.

Poetry doesn't use setup.py, instead relying on the PEP 518 `build-system` directive. I don't know if this would require specifically adding a special case for Poetry, or if it's possible to extract the needed information from a Poetry build artifact without needing any knowledge of Poetry's internals.

**Comment by freakboy3742** [comment]
Thanks for the report/suggestion!

Your mention of PEP518 is prescient. I've been having a lot of conversations about Briefcase with folks involved with the PyPA, and it's become increasingly clear that Briefcase *is* (or, at least, *should be*) a PEP518 build tool - that is, Briefcase is a *competitor* (in the friendly sense) to Poetry, not something that needs to "use" Poetry.

Poetry (and distutils for that matter), is a tool for managing your requirements, and then turning your "directory of code" into a wheel. That wheel is the distribution artefact for your project; that wheel is then uploaded to PyPI.

Briefcase has a different use case. The distribution artefact of Briefcase is a platform installer. If you're using Poetry, you're intending to push your code to PyPI; if you're using Briefcase, you're intending to push your code to an App Store. You don't use Briefcase to turn a wheel into an installer; you create an installer *instead* of the wheel.

There are a limited number of projects that might need both - for example, a developer tool might need to be pip installable *and* installable from an app store; but in that case, you're really looking at using Poetry *and* Briefcase, rather than "Briefcase supporting Poetry" or vice versa. I'm not completely sure how this would work, though; PEP518 doesn't seem to allow much flexibility around the idea of supporting multiple build tools.

I'm about to start on a big rework of Briefcase which will use pyproject.toml as a configuration format. I'm going to close this ticket for now, as there's no immediately actionable fix; but as I work on the rewrite, I'll definitely be looking for ways to maximize compatibility with Poetry.

**Comment by jtrakk** [comment]
At the least, I hope I can continue to use `poetry add` as my single tool for managing dependencies, and the `[tool.poetry]` namespace for project metadata such as author, description, and all that jazz.

**Comment by freakboy3742** [comment]
From an end user perspective, that makes perfect sense; however, it reveals a separate UX concern. Why would the configuration items for *briefcase*  be contained under the tool heading for *poetry*? 

I'm not sure what the right answer is here, and it might require some greater cooperation between tools.

**Comment by jtrakk** [comment]
My current theory is that Poetry is a tool for managing package development, and it happens to have a convenience command for uploading wheels to PyPI. 

If briefcase were to use `pip install .`  to get the package metadata and pull the data out of the dist, it wouldn't need to know about what tool the package uses (distuils, setuptools, flit, poetry). Maybe it would be convenient to have a common build-system API for extracting package metadata without (explicitly, at least) building a dist. The new `importlib.metadata` comes to mind.
