### ISSUE TITLE
when I use psutil I can't run 'briefcase run', but 'briefcase dev' works well

### ISSUE THREAD

**Issue by lpchg1992** [beeware/briefcase#313]
I'm a new programmer, I met an issue just like the title said, and the console didn't give me any information but 'Unable to start app ****'. I work on Windows 10, use VScode with python3.7.

when I remove the psutil and its relative function, I can do both 'dev'  and 'run', also 'package' and finally install.

**Comment by lpchg1992** [comment]
Can anyone help? After following the step in #issue314, I still can't find the bug log.
```
def shutdown_jupyter(self, widget):
        try:
            for proc in psutil.process_iter(['pid', 'name', 'username']):
                if proc.info['name'] == 'jupyter-notebook.exe':
                    keyPid = proc.info['pid']
                    break
        except Exception:
            keyPid = False
        try:
            if keyPid:
                os.kill(keyPid, -9)
                srv = '*******'
                self.main_label.text = srv
            else:
                srv = '************'
                self.main_label.text = srv
        except Exception:
            srv = '*********'
            self.main_label.text = srv
```
And here is the function where the `psutil` used in my code. I need a direction to solve the issue, Could someone just give me a tiny suggestion? Thanks!!!!

**Comment by freakboy3742** [comment]
So - the details listed on #314 won't help in this case, because you're not actually outputting anything to console. If psutil is raising an exception, you won't be seeing it, because you're catching the exception, and not outputting anything to say that you have caught the exception, or what the exception is.

So: the first thing to try will be to modify `except Exception` to:
```
except Exception as e:
    print("ERROR": e)
```
That will give you console output when a problem occurs, rather than silently hiding the problem.

However: my guess would be that you haven't configured your app to include `psutil`. `briefcase dev` runs in your local virtual environment, so if psutil is installed, it will work fine. However, if your `pyproject.toml` file doesn't list `psutil` as a requirement, then it won't be present in the app that is used when you run `briefcase run`.

**Comment by lpchg1992** [comment]
Great thanks first! I solved this issue caused by my misunderstanding of the file pyproject.toml.
