### ISSUE TITLE
Tutorial 1: Your First App. Issue with briefcase usage in Windows

### ISSUE THREAD

**Issue by Guppy16** [beeware/briefcase#326]
I followed the instructions in tutorials 0 and 1 for a windows installation of beeware using pip.
However, I couldn't set up the app with "briefcase new". Instead, I had to use "beeware new".
However, the next command, "briefcase dev" doesn't work. It seems that a briefcase.exe file wasn't created in my venv\Scripts folder. Also, a __main__.py is missing from venv\lib\briefcase
This is the link to the tutorial: https://docs.beeware.org/en/latest/tutorial/tutorial-1.html

**Comment by freakboy3742** [comment]
If `beeware new` works, but `briefcase new` doesn't, you've installed the wrong version of Briefcase. When you install briefcase, you need to pass in a `--pre` option (install pre-release). This will install the 0.3.0 version, rather than the 0.2 version. This *is* in the tutorial, but it's easy to miss if you read the instruction a "pip install briefcase" (which would be the "normal" install process for a Python tool)

You can either start the tutorial from scratch, creating a new virtual environment; or, you *should* be able to upgrade by running `pip install -U --pre briefcase` to upgrade briefcase to the 0.3 version.
