### ISSUE TITLE
Call "briefcase create" during CI/CD workflow in Windows virtual machine

### ISSUE THREAD

**Issue by saroad2** [beeware/briefcase#356]
I'm in some problem calling "briefcase create" in my CI/CD process.

In my "publish" job I want to publish the "*.msi" file of my project. In order to do that I need to call briefcase create+pacakge in Windows virtual machine.

the problem is that "briefcase create" requires Wix Toolset in windows, which I don't know how to install in the command line of my CI/CD workflow.

Do you have an idea of how to approach that? Is it even possible to download Wix Toolset from the command line? Any help would be appreciated.

It is worth mentioning that I'm using the CircleCI CI/CD platform.

**Comment by freakboy3742** [comment]
Unfortunately, I can't say I know. 

You can definitely *download* WiX from the command line (you can point curl/wget/any other downloader at the public download URL). Installing it is another matter entirely. As I understand it, MSI installers are *supposed* to be scriptable - but I have no idea how that is acheived. Someone with Windows sysadmin experience might be able to help.

Another option *might* be to install the app on a physical machine, then zip up what was installed, and unpack *that* into your CI environment. I don't *think* WiX does anything with the registry during install that is critical - you only need access to the executables, and the WIX_HOME environment variable set.

If you find an answer, I'd definitely be interested in hearing about it, though. I'd like to be able to document how to do automated releases using CI platforms.

**Comment by paulproteus** [comment]
Hey @saroad2 ! Cool that you're setting this up. I've done some Windows stuff and thought I'd chime in, in the hopes of being useful.

If I'm looking at the right page, https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm shows they distribute some ZIP files as well as an EXE.

It looks to me that if you download `wix311-binaries.zip` and unzip them in your CircleCI configuration, and if you can put the binaries in a place briefcase will find them, then that'd be what you want.

Let me know what you think. Happy to help more if desired, or hop on a call/video chat if you want another pair of eyes.

**Comment by saroad2** [comment]
Hi there @paulproteus ! Thanks for the input.

I did some research and found out [here](https://chocolatey.org/packages/wixtoolset) that Wix Toolset can be installed using the following command:
```
choco install wixtoolset
```
I haven't tried yet using it in my CI/CD workflow, but I'll update once I did.
The only thing that needs to be considered is that this command should be running as administrator, so I need to check how to do that in CircleCI

Your idea sounds like it should work, but I don't feel comfortable saving an *.exe file as part of my repo unless if I have too. It feels like a patch. If the `choco` stuff won't work, I'll consider your suggestion again :)

In any case, I'll keep you updated!

**Comment by paulproteus** [comment]
Great! Just to clarify one thing about my suggestion:

> Your idea sounds like it should work, but I don't feel comfortable saving an *.exe file as part of my repo unless if I have too.

What I intended to say was that your CircleCI config could include something like this PowerShell fragment:

```
Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
unzip wix.zip
```

i.e., you wouldn't save Wix code into your repo, but you'd download it and unzip it in your CircleCI config.

Your way sounds solid, too. Looking forward to hearing what you find!

**Comment by saroad2** [comment]
Hey, @freakboy3742 asked me to share with you my user story, so here it is:

Our story
I'm a physics student at Tel Aviv University and an algorithms engineer at Salesforce. During my study at the university, I came across the need to fit experimental data to theoretical formulas. The university provided us with a very primitive Matlab code that can do this, but this code has been written 20 years ago… I found it very insufficient for my needs and my fellow students’ needs.

So I wrote a new python library called [Eddington](https://github.com/EddLabs/) that does exactly that. It wraps up Scipy, Matplotlib, and NumPy in a very easy and straight forward way and can help students fit their data very easily to the theoretical models.

After I did that, I pitched the library to the professor responsible for TAU laboratories in order to give permission for other students to use my library. I thought that most students like me need something better to work with than what they already have. After I talked to her I realized that there are 3 types of students that may use my platform:

1. Researchers that know python and would want to use Eddington as a library for their experiments analysis code.
2. Students that are familiar with programming and CLIs but not necessarily know python. They will probably feel comfortable using Eddington as a CLI.
3. Students who have no programming knowledge and need a GUI in order to operate the library.

While the first 2 were easy to implement, the third one was tricky. I don’t know how to program in javascript and felt that trying to call Matplotlib through javascript may cause some unnecessary errors. I wanted to use a GUI library which is fully written in python, a programming language that I know very well, and could be published to all known operating systems such as Windows, Mac, Linux, etc. This is why I chose “BeeWare” ad my GUI platform.

At the moment the Eddington platform is not documented at all, but it works just fine! After the COVID-19 pandemic will pass we will start beta-testing with few students at TAU, and after that, we will publish an official release of the project with full documentation.

At the meanwhile, you can take a look at [here](https://github.com/EddLabs/eddington_gui) to see how Toga and Briefcase are being used as a GUI platform in my project. Maybe you can give some feedback on how to use it better. Pay attention that I’m developing on Windows, therefore I’m not using the full power of Toga because not all features are yet available for Windows. I’m trying to keep contributing to the BeeWare project what I need along with my work on Eddington.

**Comment by freakboy3742** [comment]
@saroad2 That's awesome - thanks for sharing! 

For the record, it sounds like you're *exactly* the type of user that BeeWare is pitched at. My own background is in Physics (although I'm *long* out of practice :-) ) so I'm well aware of the extent to which people in the sciences are smart and capable, and often know Python. And if they don't, they're entirely capable of learning it - and they're often quite motivated to do so because of the wealth of numerical processing and other data analysis tooling that exists. 

People with a science background also part of a "long tail" of app developers - people who have extremely specific application needs that aren't *inherently* complicated, but that will *never* be satisfied well by a general purpose tool. That makes a graphics toolkit that makes it easy to develop GUIs a valuable resource.

In terms of what you could be "doing better" - I've only taken a quick look, but nothing obvious stands out. Plus, you've got this working on Windows, which is the backend that has seen the least ongoing maintenance - so that's more than a little impressive :-) If you're comfortable having Eddington on the Briefcase & Toga success stories page, I'd love to add it.

One thing I would suggest as a potential larger project: Toga *has* a canvas widget that is implemented on macOS and GTK - and we've also had [a contribution that allows that canvas to be used as a matplotlib rendering backend](https://github.com/beeware/toga_chart). That charting widget hasn't been looked at in a while, and the canvas obviously isn't implemented in Windows at this time - but... if someone wanted to look into that... :-) 

I know that might *sound* like a big project, but I believe it should be a lot less scary than it sounds. The GTK implementation of canvas is 160 lines of code. There's a base problem of picking Winforms widgets to implement the Toga API, but it looks like Winforms has a couple of obvious candidates (`System.Windows.Controls.Canvas` and `System.Drawing.Graphics` being the two I can see). After that, it's mostly a matter of working out "how do I spell 'draw a red line from A to B' in Winforms".

**Comment by saroad2** [comment]
Hey. Thanks for all the compliments! This is really exciting :)

If you wish, you can surely add Eddington to Briefcase & Toga success stories page (even though I don't see it as a success story yet since I'm the only user of it at the moment. maybe in a few months).

As for Canvas implementation in Windows, please open an issue for it and assign it to me. I'll give it a go. If I could make Matplotlib work with a canvas widget, that could be awesome!

Thank's for all the support. I hope to continue contributing to your project, and myself in the process. My CI/CD workflow should be completed soon and I'll post here a link so you could take a look at it.

**Comment by saroad2** [comment]
So I promised you I let you know when I have a working CI/CD process. So I have one!

Unfortunately, CircleCI does not support guest view mode so you cannot see the actual job in action, but if you take a look [here](https://github.com/EddLabs/eddington_gui/blob/dev/.circleci/config.yml) and see the config file defining the jobs.
As you could see the "publish" job creates and deploys the *msi* file as part of the [release](https://github.com/EddLabs/eddington_gui/releases).

Thank you for your help! Keep the good work. I will try to contribute my part as much as I can :)

**Comment by freakboy3742** [comment]
Awesome! Thanks for sharing.

At this point, it would appear that there's nothing directly actionable on the part of Briefcase as a project. Your config demonstrates CI/CD is possible; anything beyond that is going to be a function of the exact CI/CD system in use. 

On that basis, I'm going to close this ticket; if you think there are other features that should be added to support CI/CD configurations, please open a new ticket.
