### ISSUE TITLE
briefcase build fails with missing dependency to libgdbm_compat.so.3 on Ubuntu

### ISSUE THREAD

**Issue by Avagenzo** [beeware/briefcase#357]
OS: Ubuntu 19.10
Python Version: 3.7 (created by Anaconda)

I followed the tutorial on [Beeware tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-3.html) and tried to build the app with `briefcase build`. This didn't work. I get the following error in the console:
```
...
Deploying dependencies for ELF file <...> AppDir/usr/lib/python3.7/lib-dynload/_dbm.cpython-37m-x86_64-linux-gnu.so 
ERROR: Could not find dependency: libgdbm_compat.so.3 
ERROR: Failed to deploy dependencies for existing files 
```
... so i tried a different python version (switched from 3.7 to 3.6). No success.

I found the note in the tutorial that says 

> Packaging binaries for Linux is complicated

and gives four options. I chose option 4 and followed these steps: [Python-Linux support package](https://github.com/beeware/Python-Linux-support/tree/3.7)

I replaced all files in my linux directory with the ones i found in the dist folder created by docker but still get the same error. Any ideas?

**Comment by freakboy3742** [comment]
Thanks for the report! This is definitely an area where we need more real-world testing.

If you literally followed the instructions on the Python-linux-support page (including the docker bits), you'll actually be building a 16.04 build, not a 19.10 build (i.e., you'll be reproducing what you get by default from Briefcase, not building a custom support package for 19.10). This is definitely an oversight caused by the documentation for the support package; I'll make a note to update those docs.

You have a couple of possible options.

1. Modify the Python-linux-support Dockerfile to use 19.10 as a base, rather than 16.04.

2. Do the build that the Dockerfile describes, but *outside* docker (i.e., run the build in your *native* 19.10 environment, rather than inside Docker.

3. Run the *Briefcase* build inside a 16.04 Docker container (this is effectively option 3 from the tutorial)

The key is to make sure that the Ubuntu environment used to build your support package is the same Ubuntu environment used to build your AppImage. 

Hope that helps!

**Comment by Avagenzo** [comment]
Awesome, thank you for the hint. Didn't check the Dockerfile. I had to keep the `os.py` file in ... /lib/python3.7/os.py.  though. Also docker doesn't like the upper case in

`docker build -t beeware/Python-Linux-support .`

i got it running with: 

```
docker build -t beeware:python-Linux-support .
docker run -it -v `pwd`/downloads:/local/downloads -v `pwd`/dist:/local/dist beeware/Python-Linux-support
```

I'll close the issue, cause its solved.
