### ISSUE TITLE
platform-specific template override?

### ISSUE THREAD

**Issue by tlambert03** [beeware/briefcase#408]
we might want to provide a template override just for windows, while using the default template for all other platforms.  I see that I can pass `--template` to `briefcase new`, and I can provide a template url in the `pyproject.toml` options ... but it's unclear how to achieve the same platform-specific template that the default option achieves with `https://github.com/beeware/briefcase-{self.platform}-{self.output_format}-template.git` (without having to provide our own template for ALL platforms... not just windows), using either of those two options.  suggestion?

**Comment by GenevieveBuckley** [comment]
Are we not able to put the template url under the platform specific section of pyproject.toml (eg: `[tool.briefcase.app.napari.windows]`)? That really seems like it should work out of the box.

Also, unless I am mistaken, I think that the `--template` option in `briefcase new` is not what you want. You use that to point to another cookiecutter generating the project repo structure. (I'm assuming this issue is because you're tweaking the `briefcase-windows-msi-template`, which doesn't come into play until you run `briefcase create`)

**Comment by tlambert03** [comment]
the platform-specific section (`tool.briefcase.app.appname.windows`) is what I was looking for.  thanks @GenevieveBuckley
