### ISSUE TITLE
Add a mechanism for detecting if an code is running as a bundled app

### ISSUE THREAD

**Issue by tlambert03** [beeware/briefcase#412]
Apologies if I missed this in the docs... curious if you have a recommended (cross-platform?) approach for detecting whether a python app is being run from inside of a briefcase app?  something like the equivalent of `getattr( sys, 'frozen', False )` in pyinstaller?

**Comment by freakboy3742** [comment]
We can't really provide an API (like the `frozen` property), because there's no runtime component to briefcase - it's "Python running as normal", but packaged for isolated distribution.

However, there are some side effects of operation that could be used to infer Briefcase packaging. The best I can think of would be to use metadata of the app module:
```
import sys
try:
    from importlib import metadata as importlib_metadata
except ImportError:
    # Backwards compatibility - importlib.metadata was added in Python 3.8
    import importlib_metadata

app_module = sys.modules['__main__'].__package__
in_briefcase = 'App-ID' in importlib_metadata.metadata(app_module)
```
This relies on two properties of Briefcase:

1) Briefcase always starts an app with `python -m myapp`; this results in `__main__` being set to `myapp`. 
2) When Briefcase installs your app, it adds a PEP566 metadata file for the app module. That will include some tags in valid PEP566 format, but that a "normal" installed library won't have. `App-ID` is probably the best option; `Formal-Name` would also work. If `App-ID` is defined, you've got a Briefcase app; if you don't, you don't.

I guess it wouldn't hurt to add an explicit tag to the app module metadata that tracks the Briefcase version that was used to package the app (i.e, `Briefcase-Version: 0.3.0`); that would be a guaranteed reliable marker, rather than an accidental side effect.

The meta-question I have is the use case for this. In the case of PyInstaller, the app freezing process can introduce significant differences in the runtime operation of the app. However, Briefcase shouldn't (to the best of my knowledge) have any of those differences - as I said, it *should* be "Python running as normal", but packaged for distribution. Can you elaborate on the reason you want to detect Briefcase packaging at runtime?

**Comment by davisagli** [comment]
I'm not using briefcase yet but am evaluating it. One reason our app might want to be able to do this would be so that the app can provide contextual instructions for how to update the app based on whether it was installed with briefcase or not.

**Comment by freakboy3742** [comment]
@davisagli That makes sense; and I can imagine other use cases that are in a similar. 

On that basis, I think it makes sense to add an explicit metadata flag for `Briefcase-Version` that can be used for runtime identification purposes. Combined with some documentation, that sounds like it will address this use case.

**Comment by tlambert03** [comment]
sorry, I forgot to add on my use case.  What @davisagli said applies in my case as well.  We also found that `sys.path` and the relationship between files was different enough (on windows) between bundled versions and pip-installed versions that in order for our plugin architecture to work, we have to make special considerations when running in a briefcase app.
