### ISSUE TITLE
Can't use briecase with python 3.8 du to _.pth python bug

### ISSUE THREAD

**Issue by jgirardet** [beeware/briefcase#453]
There is a regression in python 3.8 where  python38._pth is ingnored, so packaged path are wrong.

I  post it in case of  someone  is dealing with same  bug.

https://bugs.python.org/issue41304

I'll close the issue with the next python release (the patch is already here https://github.com/python/cpython/pull/21495)

**Comment by freakboy3742** [comment]
Thanks for the report (and reporting it upstream, too!)

This effectively means Briefcase won't work on Python 3.8 until 3.8.5 is released, which is a little annoying. However, the CPython ticket suggests a workaround: moving to using `python._pth`. 

We could adapt Briefcase to use that name without any real difficulty. So:
 * If there's a `python._pth` *and* a python38._pth - which one takes priority? Do they both run?
 * Does `python._pth` work on Python 3.5/3.6/3.7?
 * Does `python38._pth` work on Python 3.8.0/3.8.1/3.8.2/3.8.3? (i.e., when was this regression introduced?)

If this is a change we can make to use `python._pth` instead of the versioned version, that's a trivial fix. If we need to remove the older versioned version as well, that's not *that* much harder. If we need to *only* do this for specific Python 3.8 revisions.. .that's possible, but annoying.

**Comment by zooba** [comment]
The regression was very recent - 3.8.4 is the only released version that included it, and 3.8.5 will have a fix (I'm about to go sound out the release manager on doing a quick release).

`python._pth` is really `{argv[0].stem}._pth`, so it will only be `python._pth` for `python.exe`.

Both filenames were supported from 3.6 onwards - prior to that there was no support for this at all - and the DLL-based name has always taken priority (so that you can lock down a shared DLL, even if someone loads it using a different executable).

**Comment by freakboy3742** [comment]
@zooba Thanks for that detail. If that's the case, then I can flag 3.8.4 as a problematic release, and prevent it from being picked up by Briefcase.

**Comment by freakboy3742** [comment]
@jgirardet I've now marked Python 3.8.4 as a problematic release for Windows, so this problem should be resolved. The support packages are maintained independent of Briefcase itself, so you don't need to update Briefcase; rebuilding your Windows app should be sufficient. 

If you continue to see problems, let me know and I can re-open this ticket.
