### ISSUE TITLE
appImage build regression in 0.3.3

### ISSUE THREAD

**Issue by jgirardet** [beeware/briefcase#456]
Hi,
ubuntu 20.04 on github actions
was ok with 0.3.2
full log : https://pastebin.com/RRa0uE4J
```
last error : ERROR: Could not find dependency: libGL.so.1 
```

**Comment by freakboy3742** [comment]
It's very difficult to diagnose a bug without full reproduction instructions - "it's a regression" with an error log doesn't really tell us what you were doing to *cause* the regression. It's also difficult with what appears to be a partial log - the pastebin appears doesn't appear to start at the beginning of a create command.

However, in this case, I suspect that all we've done is surface a bug that existed previously, but wasn't obvious. The stack trace you've provided is complaining about `libGL.so.1` not being available - but that's the *only* reference to `libGL.so.1`, which means it isn't being packaged as part of the app itself. This means it needs to exist in the build environment.

`libGL.so.1` won't be in the default build environment unless it's been explicitly added as a system requirement (the `system_requires` definition in `pyproject.toml`). This wouldn't have been detected as a problem on Briefcase 0.3.2 because we weren't fully localizing all binary libraries. As of 0.3.3, we are; and as a result, the missing dependency has been identified by the build.

**Comment by jgirardet** [comment]
I'm sorry if the report was incomplete or too rough.

That was it indeed. I think we should/could add in the doc something like it :
```
Sometime, running dev mode will pass but when bulding the app you could  get  an error message like :
Could not find dependency: someLIB.so.1 
it's probably due to a dependency existing inside the dev environment  but which needs to be added in the building environment, via  `system_requires` in pyproject.toml
You can find the missing dependency by searching https://packages.ubuntu.com/ (select xenial)
```

**Comment by freakboy3742** [comment]
There's probably 2 pieces of documentation required -

1) An update to the [existing reference guide](https://briefcase.readthedocs.io/en/latest/reference/platforms/linux/appimage.html#system-requires) clarifying what happens if you don't define all your requirements.

2) A new "HOWTO" guide covering how to resolve common problems during the development process. This could be split up by platform - the error you've reported here, for example, won't ever occur on macOS; providing a way for people to easily narrow down on errors will be important.

**Comment by salotz** [comment]
I hit this following the tutorial on linux. Maybe it should be either part of the tutorial or the  `pyproject.toml` that gets generated on `briefcase new` and choosing PySide2.
