### ISSUE TITLE
Which GUI libraries briefcase supporting

### ISSUE THREAD

**Issue by myounus96** [beeware/briefcase#488]
This is not a feature request but just a question, as it is not mentioned in docs, and from going through the issues I got Tkinter is not supported, but I wanna know which ones are supporting, from famous ones like wxpython, pyside2, pyqt, pyGui..?

**Comment by freakboy3742** [comment]
There's two answers to this question.

Conceptually, Briefcase *should* be able to support *any* GUI framework - *including* Tkinter. Briefcase has no *specific* ties to any widget toolkit. As long as you can `pip install` the framework (i.e., there's no requirement to install something using a mechanism other that pip), you *should* (bugs notwithstanding) be able to package the app with Briefcase.

Our wizard includes a couple of frameworks (Toga, PySide, PPB) - but that's purely a templated started point. If you want to use WXWindows, you can - use the "empty" template, and add whatever app-specific code you want; or construct your `pyproject.toml` file by hand. If you're enthused to submit a template for WXWindows (or another toolkit), we'd love to add it to the options that are available in the wizard.

To be clear, though - that *doesn't* mean that Briefcase will be able to package PySide, TkInter, or WXWindows apps on Android or iOS. Briefcase can't manufacture platform support that doesn't exist. It's purely a packaging tool, and if the library doesn't *already* support iOS or Android, then there's not much Briefcase can do about that.

In practice, we're not putting a lot of effort into Tkinter because although it's a CPython builtin, it's a little painful to package all the Tk dependencies in an isolated way. It's certainly *possible* - we just haven't got the resources (or enthusiasm) to do that piece of work. If someone is particularly motivated to support Tkinter, we'd definitely encourage them to do so. The underlying task is to build a Python support package that includes Tk and all it's dependencies. At present, we deliberately strip out Tk support from the Python support build.

Procedurally closing this PR; if you've got any follow up questions, feel free to post them an we'll respond.
