### ISSUE TITLE
Huge Build size for windows

### ISSUE THREAD

**Issue by myounus96** [beeware/briefcase#492]
Hi there, I just completed the tutorial and build size of .MSI of basic hello word app is `125mb`, is this expected..?

**Comment by myounus96** [comment]
I selected PySide2 at project creation time.

**Comment by myounus96** [comment]
I also tried with WxPython, the MSE size is 45mb, so it is because of pyside2 dependencies.

**Comment by freakboy3742** [comment]
Sounds like it. The Toga Hello World is about 9.5MB. 

I suspect the extra size comes from the binary dependencies of WxPython and PySide2/Qt respectively. You might be able to prune those down manually, but you'll need to speak to the maintainers of those frameworks for guidance on how to do that.

Closing since ticket the briefcase is "working as expected" in this case, and the problem exists with dependencies that are outside the control of BeeWare.
