### ISSUE TITLE
Is there a more efficient way to implement BeeWare?

### ISSUE THREAD

**Issue by PROgramJEDI** [beeware/briefcase#502]
I don't really use BeeWare before (now I plan to) and I'm not sure how it compiles the code whether it's done using "briefcase" or "rubicon-java". These days I'm learning Cython, and I was wondering if it's possible to compile a full mobile app into C/C++ since Cython already does most of the work (and really good work). If it is, I'll be more than happy to try and improve BeeWare, such that it will perform even better than Java, C# on mobile devices, and expand the python community to this field.

**Comment by freakboy3742** [comment]
Briefcase/BeeWare apps contain no* compiled components. Everything is done at runtime with ctypes/ffi introspection of runtime libraries; this allows BeeWare apps to be pure Python. 

(* ok; Rubicon-java and Pythonnet contain a small compiled shim; however that shim is the same for every app, and doesn't require recompilation. However, GTK, iOS and macOS apps are pure Python)

We made a very conscious decision to *not* use Cython, as it massively complicates the build and deploy process; and for the types of applications that we're building, Cython doesn't actually give you that much of an advantage. 

Cython's gives benefits where you're able to exploit CPU-level instruction parallelisation - that's why it's beneficial in math/computational environments. However, GUI apps don't gain much from that kind of optimization.

It is *possible* to compile an app with Cython; however, that's not a direction that BeeWare is interested in pursuing.
