### ISSUE TITLE
yahoo_fin module

### ISSUE THREAD

**Issue by El-Vegas** [beeware/briefcase#507]
I just started a tutorial about how to work with beeware/briefcase and it worked fine until the end when I typed "briefcase run" and got an error where it says that my module couldn't be found. Module is yahoo_fin. However, when I run "briefcase dev" the program works flawlessly. Why does "briefcase dev" command work and "briefcase run" doesn't? Could it be that yahoo_fin module is not supported? If so, when will it be included?

Thanks

**Comment by freakboy3742** [comment]
The problem is almost certainly that you haven't added `yahoo_fin` to the requires list in your `pyproject.toml`. When Briefcase creates the runnable version of your application, it creates a completely isolated runtime environment - so you need to declare all your dependencies. `briefcase dev`, however, runs in your current development environment. If you've manually installed `yahoo_fin` into your virtual env, but *haven't* added it to the `requires` list, the app will fail during `run` because the packaged version of the app *doesn't* have the requirement installed.

So - add `yahoo_fin` to the app-level `requires` list in `pyproject.toml`; run `briefcase update -d` (to force the installation of dependencies); then `briefcase build` to rebuild the app bundle; and finally `briefcase run`.

**Comment by El-Vegas** [comment]
Thanks! It worked.
