### ISSUE TITLE
Share built dependencies between two apps

### ISSUE THREAD

**Issue by NHPatterson** [beeware/briefcase#509]
**Is your feature request related to a problem? Please describe.**

Sorry if this already exists, I couldn't find any information. Is it possible to share the built dependencies for two apps? My concern is packing the same dependencies for two apps to be distributed together doubles the footprint needlessly.  Also is there another forum for these sorts of questions? Thanks!

**Describe the solution you'd like**
Two apps from one project that used the same built dependencies.

**Comment by freakboy3742** [comment]
Thanks for the question - and yes, this is the right place; we're using GitHub tickets for support questions. There's also [Gitter ](https://gitter.im/beeware/general) if you want "realtime" chat.

Yes, including all the dependencies in every app increases the installed footprint of an app. However, that's also by design. 

Briefcase is explicitly solving the "install an app from the App Store" problem - and that style of distribution *requires* apps be entirely self contained. Modern App Store expect this; you can't install app A and have it not work unless app B is also installed. On mobile platforms, sharing of this kind is near impossible due to app sandboxing.

Yes, this means some duplicated disk space. Our plan is to focus more on tree shaking and related approaches for minimising the bundle size, rather than trying to force mechanisms for sharing code between apps. 

If you *do* want to share packages between apps, you're not really looking at app distribution - you're looking at deployment configuration. Tools like pip/poetry/pipenv already exist to managing this.
