### ISSUE TITLE
Running APK in Nox Android Emulator

### ISSUE THREAD

**Issue by EdLipson5117** [beeware/briefcase#531]
I am new to briefcase and BeeWare. I'm trying a simple experiment with Hello World and Temperature Conversion samples before I begin any significant development applications. 

My two apps build and run locally on my Windows 10 PC (Python 3.7), and run in the android emulator. I wanted to try in a separate emulator to determine if it is a viable platform for pre-deployment testing. briefcase package android creates a aab file. I used bundletool to create the apks file
   java -jar bundletool.jar build-apks --bundle=app-release.aab --output=app-release.apks --mode=universal
and then unzip the universal.apk from the apks.
The apk loads into Nox but crashes at the splash screen when started. I have not tried to run in developer mode on my actual android phone as it is my phone and I don't want to mess that up too badly.

Is this an expected behavior? Any suggestions for alternate methods?
[C_Users_edlip_Documents_code_Android_tempconvert_src_tempconvert_app.py__20201118092616_551.pdf](https://github.com/beeware/briefcase/files/5560639/C_Users_edlip_Documents_code_Android_tempconvert_src_tempconvert_app.py__20201118092616_551.pdf)
[c_Users_edlip_Documents_code_Android_helloworld_src_helloworld_app.py__20201118092528_549.pdf](https://github.com/beeware/briefcase/files/5560640/c_Users_edlip_Documents_code_Android_helloworld_src_helloworld_app.py__20201118092528_549.pdf)

**Comment by EdLipson5117** [comment]
Sorry, I don't know how to change the label

**Comment by freakboy3742** [comment]
It's not entirely clear what you're trying to do, or what it is you're trying to get help with.

I've never used Nox, so I have no idea if it has any special requirements. You're on your own there - I can't comment on what is "expected behavior". I also have no experience with `bundletool` - Briefcase manages the process of creating bundles as part of the `briefcase publish` command.

You've also added that you "don't know how to change the label"... which label are you referring to?

If you're getting a crash on startup, then the first place to look will be the logs; `adb logcat` would normally be the way to access those logs, but again - I have no idea if that is an appropriate instruction for Nox, as it's not a tool we use or recommend.

I would add that the risk of enabling "developer mode" is *extremely* low. Phones are *very* hard to break, unless you're *actively* trying to do so. Developer mode allows you to upload an APK via the USB cable, and get diagnostic information over that USB cable. If you upload a bad app, you can delete that app. The apps themselves are sandboxed. You would have to actively *try* to break your phone by uploading an app.

If you're really paranoid, you can turn it off after each debugging session. Going to extraordinary lengths to avoid developer mode seems to me like energy that would be better spent elsewhere.

**Comment by freakboy3742** [comment]
Closing as the original question has been answered.
