### ISSUE TITLE
Scan for the installed android tools

### ISSUE THREAD

**Issue by Scot-Survivor** [beeware/briefcase#545]
**Describe the solution you'd like**
When running `briefcase create android` the tool installs and downloads the NDK SDK and other android dev tools. However I already have these on my system. It would be cool if the tool would ask/scan your system to see if it can find the tools its looking for. If it finds the tools then it can configure its self to point to those said tools.

**Describe alternatives you've considered**
Now it could be possible that there's a config setting I missed to point to already installed tools. Through my checking, I couldn't see those settings. So having a setting to be able to change where your SDK/NDK etc... are would also be a nice touch.

**Comment by freakboy3742** [comment]
Good news - this feature already exists! If your environment contains a definition for `ANDROID_SDK_ROOT`, Briefcase will use your existing install, rather than download its own copy. I believe this environment variable *should* be set as part of the normal Android Studio installer.

The same is also true of `JAVA_HOME` for Java, and `WIX` for WiX (used by Windows installers).

If this isn't working, or you've got any specific suggestions for additional auto detection schemes, we're happy to consider adding them.

I'm going to close this ticket since the feature as stated already exists; if you've got a specific suggestion for an improved detection scheme, we can open a new ticket.
