### ISSUE TITLE
Feature - pyodbc with DB connection

### ISSUE THREAD

**Issue by horphi0815** [beeware/briefcase#548]
Hi guys,

thx for this awesome app.

Do you plan to integrate a driver for handling ms-sql connections in the framework?

Best regards,

Phil

**Comment by freakboy3742** [comment]
Thanks for the kind words!

We don't have any plans to specifically integrate PyODBC into Briefcase; Briefcase is a packaging tool, so the goal isn't to "add capability to Briefcase", but to ensure that any legal Python code can be packaged with Briefcase. 

Similarly for Toga - Toga is a GUI toolkit; a GUI toolkit doesn't need a database connection, but it should be able to integrate with data that comes from *any* database library.

So, broadly speaking, anything that prevents Briefcase or Toga from integrating well with PyODBC would be considered a bug; but we're not planning to add PyODBC *to* Briefcase or Toga.

To that end - Briefcase should be able to deploy PyODBC *today* on desktop platforms; if you have any difficulties, that should be considered a bug. However, it won't be able to deploy to iOS or Android. That's part of a bigger set of deployment problems involving the use of native libraries on mobile platforms, which we definitely consider a bug in Briefcase; see #471 for details.

I'm going to close this ticket since I think I've answered your question; if you've got any followups questions, feel free to continue the discussion here, or on a new ticket.

**Comment by horphi0815** [comment]
> 
> 
> Thanks for the kind words!
> 
> We don't have any plans to specifically integrate PyODBC into Briefcase; Briefcase is a packaging tool, so the goal isn't to "add capability to Briefcase", but to ensure that any legal Python code can be packaged with Briefcase.
> 
> Similarly for Toga - Toga is a GUI toolkit; a GUI toolkit doesn't need a database connection, but it should be able to integrate with data that comes from _any_ database library.
> 
> So, broadly speaking, anything that prevents Briefcase or Toga from integrating well with PyODBC would be considered a bug; but we're not planning to add PyODBC _to_ Briefcase or Toga.
> 
> To that end - Briefcase should be able to deploy PyODBC _today_ on desktop platforms; if you have any difficulties, that should be considered a bug. However, it won't be able to deploy to iOS or Android. That's part of a bigger set of deployment problems involving the use of native libraries on mobile platforms, which we definitely consider a bug in Briefcase; see #471 for details.
> 
> I'm going to close this ticket since I think I've answered your question; if you've got any followups questions, feel free to continue the discussion here, or on a new ticket.

Thanks for your extended explanation.  I understood the the different packages and tools now.
I#m looking forward for the Bug #471. ;-)

Best regards
