### ISSUE TITLE
Unable to build or run Windows apps due to pythonnet error

### ISSUE THREAD

**Issue by joo77** [beeware/briefcase#564]
tried to follow the tutorial on the beeware.gov to start using the tools. it was working fine till yesterday. Looks like pythonnet is updated today and since then it mass up everything. I'm attaching a screenshot of what I've got. Please fix
![page_1](https://user-images.githubusercontent.com/55041810/107110608-e114ce00-680e-11eb-97ba-20b5bb72432a.jpg)
![page_2](https://user-images.githubusercontent.com/55041810/107110609-e1ad6480-680e-11eb-8c85-2865d35d2716.jpg)
![page_3](https://user-images.githubusercontent.com/55041810/107110611-e245fb00-680e-11eb-982a-4a3c91edf38d.jpg)
![page_4](https://user-images.githubusercontent.com/55041810/107110612-e2de9180-680e-11eb-9af6-1a890fe3648e.jpg)

**Comment by freakboy3742** [comment]
Thanks for the report! As you've noticed, the bug appears to be due to the 2.5.2 Pythonnet release; I've logged pythonnet/pythonnet#1376 to try to get a resolution.

In the short tern, you can work around this problem by adding `'pythonnet!=2.5.2'` to the requires list after with `toga-winforms`. Pythonnet is usually installed as a dependency from toga-winforms; Pythonnet 2.5.1 *does* have wheels available, so as long as Pythonnet 2.5.2 is flagged as a "bad" version, pip will avoid it when setting up your project.

**Comment by joo77** [comment]
Hi Russell,
Thanks for the reply. Can you give me more details on how to add that line to the requires list? And where can I  find that list?

⁣Best Regards;
Joziph Tadrous​

**Comment by freakboy3742** [comment]
@joo77 I'm not sure what else to say... there's a line in `pyproject.toml` that reads:

    requires = [
        'toga-winforms>=0.3.0.dev18',
    ]

Modify it so it says:

    requires = [
        'toga-winforms>=0.3.0.dev18',
        'pythonnet!=2.5.2',
    ]

That said - it looks like pythonnet/pythonnet#1376 has been resolved (or, at least there are now 2.5.2 wheels available on PyPI). On that basis, I'm going to close this ticket.

**Comment by joo77** [comment]
Great...thanks for your help.

⁣Best Regards;
Joziph Tadrous​
