### ISSUE TITLE
`briefcase create` cannot finish, stuck on input for configuring `tzdata` of Docker image

### ISSUE THREAD

**Issue by cSquaerd** [beeware/briefcase#567]
**Describe the bug**
Having written a small app, I wanted to build it for Linux. Following the tutorial in the BeeWare docs, specifically part 3, I run the command `briefcase create` command, and everything goes fine until the "Building Docker container image section, wherein I am prompted to enter a code for the timezone, but there is no response when I do so upon typing a number (2 for example) then pressing enter.

**To Reproduce**
1. Create a briefcase project with `briefcase new`
2. Run `briefcase create` to set up the build environment for releasing the app
3. Witness the Docker setup get stuck on `tzdata`

**Expected behavior**
The Docker image should just set itself up and I can move to running `briefcase build`

**Screenshots**
```
...
Setting up tzdata (2021a-0ubuntu0.18.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa        6. Asia            11. System V timezones
  2. America       7. Atlantic Ocean  12. US
  3. Antarctica    8. Europe          13. None of the above
  4. Australia     9. Indian Ocean
  5. Arctic Ocean  10. Pacific Ocean
```

**Environment:**
 - Operating System: Arch Linux, `linux-zen` kernel version 5.10.15
 - Python version: 3.9.1
 - Software versions:
   - Briefcase: 0.3.4
   - Toga: 0.3.0.dev26
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report! We've had a couple of similar reports on our chat forum recently. There's apparently an option you can pass to `apt` to disable the interactive piece of the tzdata install: https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image - we need to integrate that into our Docker image.

**Comment by cSquaerd** [comment]
Sounds good, thanks for the help; One last thing: If I'm reading this linked page right, I just add the line mentioned on it to `Dockerfile` in `linux/[My Project Name Here]/`, but then which command do I run? I've found with running `briefcase create` again it prompts me for an overwrite which erases and rewrites `Dockerfile`.

**Comment by freakboy3742** [comment]
You have two options:

You could manually modify the Dockerfile that `briefcase create` generates, then rebuild and tag the Docker image. This *can* be done, but there are a lot of options that need to be passed into the build command. You can dig into the source code (src/beeware/integrations/docker.py around line 218)

A much easier option is to clone [beeware/briefcase-linux-appimage-template](https://github.com/beeware/briefcase-linux-appimage-template), modify the *template* Dockerfile locally, and then add `template="/path/to/github/checkout"` to your `pyproject.toml` in the linux configuration section. This will prompt Briefcase to use your local version of the template, rather than the default Briefcase template. The template can be a local file or a HTTPS location - so you can store your modification in Github... and once that's working, you could submit a pull request containing the change :-)

**Comment by cSquaerd** [comment]
I'll give the second method a try, and see about that pull request very shortly. Thanks again.

**Comment by cSquaerd** [comment]
It seems Matt Lindesay has the same idea and prepared a pull request a week ago; Mine's basically the same, I just have `ENV DEBIAN_FRONTEND=`... instead of `ARG` at the beginning. Here's a link to his request: [](https://github.com/beeware/briefcase-linux-appimage-template/pull/7)
