### ISSUE TITLE
Macos Dropdown list had __main__.py instead of app name

### ISSUE THREAD

**Issue by ziyangczi** [beeware/briefcase#581]
**Describe the bug**
Not sure if this is solvable since python3 picks up the filename when run under "python -m" by the entry point

**To Reproduce**
1. Open the bundled app in MacOS
2. Click app name on the menubar
4. See "Hide __main__.py" and "Quit __main__.py"

**Expected behavior**
The hide and quit should both show app name under CFBundleName

**Screenshots**
![image](https://user-images.githubusercontent.com/41968256/111715807-07c11e00-882b-11eb-8b97-71322a5e03da.png)

**Environment:**
 - Operating System: MacOS 10.15.7
 - Python version: 3.8.7 (default, Jan 2 2021, 04:16:43) [Clang 11.0.0 (clang-1100.0.33.17)]
 - Software versions:
   - Briefcase: 0.3.1

**Comment by freakboy3742** [comment]
Thanks for the report; however, I'm not sure this is inside the remit of Briefcase to fix.

The contents of menus is the domain of the app itself - which, in turn, means whatever GUI toolkit you're using (PySide, in this case, IIRC). Briefcase 0.3.1 starts the app with `python -m <app_name>`; it's up to the app itself to decide what is put on menu items. Toga apps, for example, will modify this menu item to use bundle information when it's available.

That said - I'd be interested to see if this works better with Briefcase 0.3.5; we've recently made a change to how macOS packages are packaged, which means the app should present to the operating system as an actual binary with the expected name, rather than a Python script. However, I believe this then poses problems with Linux, due to some AppImage packaging issues with PySide (#470).

**Comment by ziyangczi** [comment]
Can confirm the issue is fixed in 0.3.5! I am not surprised that bundling the entrypoint through binary instead of shell script hid the executable filename well. thanks for the pointer!

(Now I just need to figure out how to unpin the version... we have been strugging to upgrade to 0.3.2 and above, will have to relook again on this)
