### ISSUE TITLE
Can't read relative file path into beeware/briefcase project

### ISSUE THREAD

**Issue by arausch335** [beeware/briefcase#601]
**Describe the bug**
Packages installed (in requirements): Kivy, pandas
app.py path: AppName/project/src/projectName 
.kv file, .csv file, icon path: AppName/project/src/projectName/resources
I am trying to access these files to use in my gui. Whenever I try and load them in, I get a `FileNotFoundError`.  I can use the full path but that wouldn't work on other devices since the beginning of the path would be different. I tried to use relative paths, like:
`self.icon = 'resources/elemental.ico'
df = pd.read_csv('resources/chemdata.csv')
kv = Builder.load_file('resources/builder.kv')`
These paths load in dev mode, but not in run mode. 

**To Reproduce**
1. Import pandas and try and read_csv a path relative to app.py
2. Or just try and access any file anywhere else using a path relative to app.py

**Expected behavior**
Expected csv or other file to load in their respective place.

**Screenshots**
![image](https://user-images.githubusercontent.com/88348187/128232734-d23fd945-4152-4d94-93a6-afa8ddef5780.png)

**Environment:**
 - MacOS Big Sur 11.2.3
 - Python version: 3.8
 - Software versions:
    - Briefcase: 0.3.5

**Comment by freakboy3742** [comment]
It's not clear to me that this is a bug. To me, it's an underspecification on the part of your code.

`resources/chemdata.csv` is a relative path. But relative to *what*? It may happen to work when code runs under `briefcase dev`, but that will be because of the specific way that `briefcase dev` is invoking your code. There will be several entirely valid ways of starting your app that *won't* work (`python -m myapp.app` and `python src/myapp/app.py` are functionally equivalent, but have different working directories).

To me, the fix here is to not rely on relative directories for packaged code - even if you're just using `os.path.basename(__file__)` as an anchor point.
