### ISSUE TITLE
requests is a pure-Python package,but I can't import it 

### ISSUE THREAD

**Issue by UnbelievableWang** [beeware/briefcase#635]
**Describe the bug**
In current version(0.3.5) ,when I try importing  requests, the app crashed

**To Reproduce**
1. add `import requests` to app.py
2. briefcase update -android -d
3. briefcase build android
4. briefcase run android

**Expected behavior**
I have read issue#471 ,so I think  it would run because requests is a pure-Python package as you mentioned 

**Environment:**
 - Operating System:windows
 - Python version:3.7
 - Software versions:
   - Briefcase:3.5
   - Toga:0.3.0
   - ...

**Comment by UnbelievableWang** [comment]
I added requires to the list,the question solved.

**Comment by freakboy3742** [comment]
I'm not able to reproduce this in my testing. I've got demo code that happily imports and uses requests on Android.

Are you able to provide the logs from the app as it runs (and crashes)? That should provide more details on what has gone wrong.

**Comment by UnbelievableWang** [comment]
Thanks. I have solved the problem. It is not caused by requests.
And, A new question arised. How can I read  file.txt in my android project? 
I tried hard to read a txt file,but failed.

**Comment by freakboy3742** [comment]
Again, it's very difficult to diagnose a problem when you don't tell us what you've done (other than "tried really hard), and more importantly, how it failed.

That said: the issue is almost certainly the path to the file being read. You can't assume the current working path for the app will be readable or writable, or will even be the path that contains app.py - especially on mobile devices. You need to construct full paths that are known to be readable and writable. Toga provides an `paths` attribute on the app that contains a number of "known paths" for your app to use - `Toga.app.paths.app` is the "app path", or the location of the folder that contains `app.py`. That location will be readable and writable on Android.

**Comment by UnbelievableWang** [comment]
Thank you very much! Your advice is helpful.
