### ISSUE TITLE
Linux on RPi build challenges

### ISSUE THREAD

**Issue by freshwuzhere** [beeware/briefcase#650]
Just attempting to get the Tutorial app working.
Built the support library on the RPi running Ubuntu 20.04.
Managed to get a build to work with a large number of library imports specifically called out.
The built AppDir needs a few manual tweaks to paths and things.
Appimage can be built with appimagetool 
When the appimage runs it cannot find some libraries with

from . import _gi
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

@freakyboy3742 said linuxdeploy could made operational by 
briefcase upgrade linuxdeploy 
but this doesn't seem to work for me - it says "Briefcase is not managing any tools."

**Expected behavior**
Tutorial App would run

**Environment:**
-  Hardware : Raspberry Pi 4 
 - Operating System: Ubuntu 20.04
 - Python version: Python 3.8
 - Software versions: 
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev20
   - ...

This problem is in a few other issue but doesn't resolve with those solutions.

Realise this is an edge case and not high priority for the project but any help or suggestions appreciated.

**Comment by freakboy3742** [comment]
I suspect the issue here will actually be upstream with LinuxDeploy - the way it makes portable linux apps is highly dependent on including and excluding specific libraries, and it's possible libffi is being inadvertently excluded.

One possible cause of this is if your Python support library has *not* successfully compiled the ctypes module - that would be transitively importing libffi, which would force your AppImage to include the library as well.

**Comment by freakboy3742** [comment]
Doing some housekeeping - closing this as a duplicate of #449.
