### ISSUE TITLE
briefcase build linux failing on ARM Mac

### ISSUE THREAD

**Issue by clstaudt** [beeware/briefcase#656]
**Describe the bug**

Building a freshly started app for Linux fails (while building for macOS works).

```
╰─ briefcase build linux                                                                                         
Unable to download https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-arm64.AppImage; is the URL correct?
```

**To Reproduce**
1. run  `>briefcase new` and configure a new project with Toga
2. run `>briefcase create` 
3. run `>briefcase build linux`

**Expected behavior**
Build app for Linux.

**Screenshots**

**Environment:**
 - Operating System: macOS 11.6.2
 - Python version: Python 3.9.7
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report. I agree this should be fixed, but it is going to be a complex problem, as it involves:
* Briefcase running on ARM hardware, and correctly identifying that it is running on ARM
* Docker running on ARM hardware, but possibly emulating x86 at runtime
* Correctly determining whether you need an ARM or x86_64 LinuxDeploy binary and support package

The short term "fix" is "don't do that" - build your Linux packages on a Linux host running on the native architecture, rather than building cross-platform (on macOS for Linux) *and* cross-architecture (on ARM for x86_64). Determining how to accurately specify the desired target platform will probably require some extra command-line configuration.

**Comment by freakboy3742** [comment]
On reflection, I'm not convinced this is actually possible in the general case - and on that basis, we should close the issue. 

The underlying problem is that `pip install` needs to be able to identify the binary platform. This is going to be problematic enough on M1 hardware; when proxying through docker and another operating system is involved, this will become almost impenetrable.

Unless this is revealed as a major need, or someone comes up with a simple and reliable solution, I'm happy to close this WONTFIX on the basis that Briefcase assumes the build platform is the deploy platform.
