### ISSUE TITLE
briefcase build android bug report

### ISSUE THREAD

**Issue by mayfan11** [beeware/briefcase#659]
1.self.question_label = toga.Label('Input a number：\r\n（1-100）', style=Pack(text_align=CENTER))

if run in "briefcase dev":
    this code run good ,and the Text auto wrap in '\r\n'
if build android and run in phone:
    the Text don't wrap in '\r\n'

2.def showresult(self):
        if self.cur_stat <= 0:
            self.exit()

if run in "briefcase dev":
    this code exit when self.cur_stat <=0
if build android and run in phone:
    Nothing happen

**Comment by freakboy3742** [comment]
If I'm understanding this report correctly, these issues are both errors of usage (and neither are related to Briefcase, AFAICT).

The first is a misunderstanding about Label; Label is, by definition, a single line of text, and should not honour newlines. We recently corrected a bug that allowed multi-line text. You don't provide any details about your platform, so I don't know which platform you've seen newlines allowed, but that is a bug in Toga.

As for the second - mobile platforms don't have any concept of an app-initiated quit, so calling `sys.exit()` is a no-op.

**Comment by mayfan11** [comment]
Thank you for your email!
About the second question:
In my phone（Android 11）,the app quits well when press the '↖' button at the bottom of the phone.
And the app re-initiate when the phone rotate.
How could I  control those behaviors by code?


btw:
How could I build different versions of Android APK?Just like Android 7,8,9..
Thank you very much again!


















At 2022-01-30 08:33:26, "Russell Keith-Magee" ***@***.***> wrote:

If I'm understanding this report correctly, these issues are both errors of usage (and neither are related to Briefcase, AFAICT).

The first is a misunderstanding about Label; Label is, by definition, a single line of text, and should not honour newlines. We recently corrected a bug that allowed multi-line text. You don't provide any details about your platform, so I don't know which platform you've seen newlines allowed, but that is a bug in Toga.

As for the second - mobile platforms don't have any concept of an app-initiated quit, so calling sys.exit() is a no-op.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freakboy3742** [comment]
> Thank you for your email! About the second question: In my phone（Android 11）,the app quits well when press the '↖' button at the bottom of the phone. 

Yes - but that's a function of the *operating system*, not the app. Show me an example of applications on Android that have a "Quit" option *that is provided in app, by the app*.

> And the app re-initiate when the phone rotate. How could I control those behaviors by code? 

At present, you don't; they're not exposed as APIs. However, even if we did support that feature, the API wouldn't go any further than setting the initial rotation and allowing/preventing rotation, rather than a "change to portrait/landscape" API. Again, orientation changes are something that is controlled by the operating system, not apps themselves.

> btw: How could I build different versions of Android APK?Just like Android 7,8,9.. Thank you very much again! 

You shouldn't need to make different versions of the APK for different Android versions; the version produced by BeeWare should be forward compatible from any version of Android from 5.0 onwards. 

If you want to set a different minimum version, you need to modify the Gradle File, and the Android support file; however, that's not a configuration we provide any explicit support for officially - because
