### ISSUE TITLE
Import Error on briefcase new

### ISSUE THREAD

**Issue by YEZaki2000** [beeware/briefcase#672]
**Describe the bug**
On entering the ''briefcase new" command, several lines show up (as shown in the following screenshots), with the last one giving an import error (cannot import soft_unicode etc..)>

**To Reproduce**
1. Go to '...'cmd prompt
2. Click on '....'enter "briefcase new" after installing it (and of course installing the beeware environment beforehands)
3. Scroll down to '....' last line

**Expected behavior**
I just wanna move forward and create a new briefcase.

**Screenshots**
![image](https://user-images.githubusercontent.com/99550520/155382769-64cdd7db-d156-47b6-8232-fe106731d6b6.png)

**Environment:**
 - Operating System: Windows 11
 - Python version: Python 3.10
 - Software versions: 
   - Briefcase:
   - Toga:
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report. I've worked out what is going on here - Jinja has a dependency on `markupsafe`; `markupsafe` has just put out a new release that isn't compatible with Jinja2 < 3, but Briefcase 0.3.5 pins Jinja to <2. 

This has been fixed in master; we've relaxed the Jinja version requirement. We're overdue for a new Briefcase release, so I'll try to get this out ASAP. Apologies for the inconvenience.

In the meantime, you can manually downgrade markupsafe to < 2.1 and the problem should be resolved.

**Comment by freakboy3742** [comment]
This has been resolved with the release of Briefcase 0.3.6.
