### ISSUE TITLE
How to get a release APK?

### ISSUE THREAD

**Issue by AndresRReina** [beeware/briefcase#708]
When running `briefcase run android` the `apk` is at `app/build/outputs/apk/debug`. When packaging with `briefcase package android` an `aab` is at `app/build/outputs/bundle/release`. This suggests debug and release versions of the built app exist. **Where can I find information about the difference between release and debug versions of a beeware app?**

If the versions are actually different, it would be useful to be able to generate `apk` release packages. I'm not planning to publish to google play, so `aab` format is not very useful as it cannot be directly deployed to a device.

So far, I've not been able to generate a release `apk`. I had expected `briefcase package android -p apk` to generate it, but `apk` is not supported (yet?). **Is there any way to generate a release APK equivalent to the `aab` file generated by `briefcase package android`?**

As a workaround, `apk` can be generated from `aab` using bundletool, but why not have the functionality in beeware?

**Comment by freakboy3742** [comment]
In terms of what is different between release and debug builds - broadly speaking, it's no different to the usual differences between debug and release builds. Debug builds include debugging symbols in the binaries; release builds have those symbols stripped. Release builds will be smaller as a result. That said, the Python Android support library used by Briefcase doesn't currently include a release version of binaries, so the release binary won't be much smaller in practice (see beeware/Python-Android-support#34)

Briefcase generates an AAB for release because that's the format the Google Play store requires; historically, APKs were allowed, but that was discontinued a year or so ago. Since the AAB is the format Google wants people to use for distribution, I didn't consider there was a whole lot of utility in supporting APK as a release format. If you think there's value in continuing to support APK as a release format, I wouldn't be opposed to adding a `-p apk` option as you've described (keeping `aab` as the default).

As an immediate workaround, if you want to generate specific targets - the fallback is to drive Gradle directly. Ultimately, Briefcase is a wrapper around a bunch of calls to native build and packaging tools; the Android backend is mostly wrappers around calls to specific Gradle targets. If you want to see how Briefcase is currently invoking Gradle, you can pass the `-vv` option to any command and it will reveal the command line that is being invoked; you can then reproduce those commands at the command line, or invoke any other commands you choose.

**Comment by AndresRReina** [comment]
Thank you for your quick response. I've managed to build directly using Gradle.

1. I've looked in briefcase code for the verbosity with `-vv` option in [src](https://github.com/beeware/briefcase/tree/master/src)/[briefcase](https://github.com/beeware/briefcase/tree/master/src/briefcase)/[platforms](https://github.com/beeware/briefcase/tree/master/src/briefcase/platforms)/[android](https://github.com/beeware/briefcase/tree/master/src/briefcase/platforms/android)/gradle.py, but could not find the code that would print the command line that is being invoked. In my computer, passing `-vv` produces exactly the same output as not passing it.
2. I think adding the `-p apk` option would be really easy to maintain as it would just need a few lines of code. I can do it and create a PR for it if you want me to.
3. If you believe adding this option is not useful, feel free to close this issue as it is already solved for me with your previous comment.

**Comment by freakboy3742** [comment]
The `-vv` option is handled at a higher level; essentially any call to subprocess catches the `-vv` option and outputs the command line being executed. 

As for adding a `-p apk` option - it's not a high priority for me personally, but I agree that it should be a relatively easy to maintain addition, so if you want to submit a PR I'll definitely consider it for inclusion.

**Comment by mzdk100** [comment]
I also encountered a similar problem. The Android application packaged through Briefcase is in aab format. I come from China and do not use Google Play in our country. Instead, we use app store such as Xiaomi Store and Huawei App Market, so I really need apk format installation packages.

**Comment by freakboy3742** [comment]
Looks like this was reported as a duplicate #1136, which has now been implemented. The next Briefcase release will allow you to `briefcase package android -p apk` to get a release APK.
