### ISSUE TITLE
Stop log streaming when app exits

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#741]
On macOS, you can run an app and see a log stream. However, if you quit the app (or the app crashes), the log stream remains, even though there's nothing to log any more.

**Describe the solution you'd like**

On desktop platforms, when the application exits, the log stream should also exit. It should *not* be necessary to hit CTRL-C to terminate the log stream; although hitting CTRL-C to prematurely terminate the log stream should remain an option.

The best fix will require identifying the process ID of the app that is started, and incorporating a monitor of that process ID as part of the log stream. An alternative (but less desirable) option would be to define a "hang up" signal that an app can include in a log stream that will be interpreted by the log stream as a "stop logging" indicator.

**Describe alternatives you've considered**

Status quo. Require ctrl-c to terminate the log.

**Additional context**

At present, this only impacts macOS. However, if #628 or #629 is implemented, it is likely the same problem will occur on Linux and Windows, respectively. 

It won't ever impact mobile platforms, because apps don't ever "exit" in the desktop sense.

**Comment by MosGeo** [comment]
Beautiful. This fixed the crash that I had on windows during exit. I am redirecting the print statements in my application to pyside widget and this caused a crash when I exited.

**Comment by freakboy3742** [comment]
@MosGeo I'm not sure exactly what bug you were seeing, but I can't see how it was related to this. The PR that closed this ticket (#742) only had a visible impact on macOS, and a potential impact on iOS (although there should be no change in behaviour). Windows has *never* used the same mechanism for log streaming; so if you were seeing a problem on Windows, I can't see how it could have been related to this.

**Comment by MosGeo** [comment]
@freakboy3742 not sure but the newest development version doesn't have the crash compared the the release version (maybe it is related to another change between release version and today). 

I know it is related to standard output redirection and closing at the end of the application. Honestly, I didn't yet investigate it fully as it didn't have an impact on the application (besides the crash when the user exits; which is invisible to the user). Now, that is gone.

In any case, I plan to recode my in-application logger to use the `logging` module instead of `print` and that should have fixed it too. I just didn't get around doing that.
