### ISSUE TITLE
No module named helloworld

### ISSUE THREAD

**Issue by sohil-hub** [beeware/briefcase#758]
**Describe the bug**
[Tutorial link](https://docs.beeware.org/en/latest/tutorial/tutorial-5/iOS.html)
I followed all tutorials from tutorial-0, and it was working fine.  In tutorial 5: taking it mobile iOS,
after running `briefcase create iOS` I got the following error.
<img width="902" alt="image" src="https://user-images.githubusercontent.com/79828293/172875867-a380eed8-9741-4588-8dc3-86f056d219d0.png">

So I had to download the support folder from https://briefcase-support.org/python?platform=iOS&version=3.7 and then replaced iOS/Xcode/Hello World/Support folder with the manually downloaded folder.

Then I ran 
`briefcase build iOS` selected iPhone11.
`helloworld briefcase run iOS -d UDID `
I got the main error.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79828293/172876596-21a94c05-9a75-4046-8970-5618fe603fc3.png">

The folder mentioned in the last line of the error contains these files.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79828293/172883467-c2b8b141-7cfd-4a82-96ce-fb5924fc2dc6.png">

**Environment:**
 - Operating System: MacOS Monterey 12.4
 - Python version: 3.7.11
 - Software versions:
   - Briefcase: 0.3.7
   - Toga: 0.3.0.dev34

**Comment by freakboy3742** [comment]
Thanks for the report.

The first error (about the support package) has been caused by a corrupted or interrupted download. Unfortunately, we don't have an automated way to clean up when this sort of corruption occurs; but if you manually delete the file in `~/.briefcase/support`, the next time you run it will download a fresh copy.

I've just done an explicit test of the tutorial running on Python3.7, and I haven't had any problems, so I strongly suspect that the second error is caused because the support package hasn't been unpacked in the way the Xcode project is expecting. The error message is somewhat misleading; the issue won't be that helloworld doesn't exist; it's that the Python interpreter hasn't started cleanly.

So - could I get you to:
1. Delete the support package from `~/.briefcase/support`
2. Delete the iOS directory that has been created in your project folder
3. Re-run `briefcase run iOS`

That should do a clean rebuild of the iOS project, which should (🤞) succeed.

**Comment by sohil-hub** [comment]
> 

Hey, @freakboy3742. 
Thanks for the help. It is working properly.

Should I close the issue?

**Comment by freakboy3742** [comment]
Awesome - glad I could help. I'll even push the close button for you! :-)
