### ISSUE TITLE
`briefcase dev` should enable all warnings

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#806]
As discussed in beeware/toga#1521, any changes to the Toga API should preserve the old API and give it a DeprecationWarning. However, DeprecationWarning is disabled by default to avoid displaying irrelevant messages to a program's end user. 

Unit test runners are only used during development, so they usually enable all warnings, but this won't be much help for Toga because user interface code isn't often unit tested. So as it stands, there isn't much chance of these warnings ever being seen.

Therefore, I think `briefcase dev` should enable all warnings, This can be done using Python's `-W` option.

**Comment by freakboy3742** [comment]
"Toga... user interface code isn't often unit tested..." *yet* :-) This is something I'm hoping to address (in the grand scheme of things). 

Regardless, there are plenty of other libraries that could be throwing DeprecationWarnings, and we're doing our users a disservice if they can't see them easily. I never really understood why DeprecationWarning was changed to be "off by default"; given that Python as of 3.7 has a flag that addresses this by enabling development mode, it's hard to argue that we shouldn't use that mode in Briefcase's Dev mode.

**Comment by mhsmith** [comment]
> "Toga... user interface code isn't often unit tested..." _yet_ :-) This is something I'm hoping to address (in the grand scheme of things).

Definitely, but I was referring to the UI code in apps that *use* Toga.

>  given that Python as of 3.7 has a flag that addresses this by enabling development mode, it's hard to argue that we shouldn't use that mode in Briefcase's Dev mode.

The [documentation of that mode](https://docs.python.org/3/library/devmode.html) says it also enables some other checks that may be "too expensive", so we'd have to measure that.

**Comment by freakboy3742** [comment]
> > "Toga... user interface code isn't often unit tested..." _yet_ :-) This is something I'm hoping to address (in the grand scheme of things).
> 
> Definitely, but I was referring to the UI code in apps that _use_ Toga.

As was I. Adding a good unit test suite for Toga itself it high on the list of priorities; but once we've built that tooling, we should be in a position to enable users to build unit tests for their own apps. I'd go so far as to say that making unit tests for GUI apps trivial could be one of the biggest growth opportunities for Toga.

> > given that Python as of 3.7 has a flag that addresses this by enabling development mode, it's hard to argue that we shouldn't use that mode in Briefcase's Dev mode.
> 
> The [documentation of that mode](https://docs.python.org/3/library/devmode.html) says it also enables some other checks that may be "too expensive", so we'd have to measure that.

Fair - if performance is really bad, then we probably don't want to turn it on (or, at least, we may want to restrict ourselves to just turning on warnings, rather than the full `-X dev` mode); but I'm willing to tolerate a lot in the name of catching problems earlier. If the performance concerns are borderline, we may want to consider adding a flag to enable/disable Python dev mode.
