### ISSUE TITLE
Add basic automated tests

### ISSUE THREAD

**Issue by eliasdorneles** [beeware/briefcase#83]
Currently, we are testing changes in briefcase manually, it would be nice to have a testing suite.

**Comment by andrewleech** [comment]
I definitely agree this would be a good idea. Automated tests especially make it easier for new contributors to get started and be more confidant their changes aren't going to break it for everyone else. Obviously this reduces the load for maintainers dramatically, especially when I keep throwing new code up every few days ;-)

Adding comprehensive test coverage to an existing project is always difficult however.  

My general plan of attack is to firstly attempt to get as close to an end-to-end integration test to cover base functionality of the entire tool/module. 

Then mandate a project policy of all new features / bug fixes having a unit test to cover the specific functionality.

FWIW I'm already planning on setting up a CI build & run (where possibly) of an example project on all supported platforms for 3.4, 3.5 and 3.6. 
It's going to be on Gitlab however because that's what I use (for everything) and it's easy to run cross-platform builds in the one pipeline. I'm aware of beekeper but I find gitlab ci stable, basically zero-config and free (for linux dockerized builds at least... and I've already got generic windows and mac build nodes).

**Comment by eliasdorneles** [comment]
Thanks for sharing your thoughts, @andrewleech, I mostly agree! :+1: 

This Gitlab thingie you're setting up for a personal project, yes?

**Comment by andrewleech** [comment]
The gitlab ci build will probably be a generic example briefcase project. 
I'm using & planning to use briefcase on a few projects and want to track compatibility, and I've wanted a complete example of many-platform tests & builds in one gitlab pipeline for some time now. This would meet both those goals. 

Ideally it'll be continuous testing of what platforms/versions are currently working with briefcase, auto synched to the upstream GitHub repo.

**Comment by jedie** [comment]
Are there any news here?

I seems that beekeeper just runs no tests, e.g.: https://beekeeper.herokuapp.com/projects/pybee/briefcase/change/d7c8555d-fe97-4788-8552-5e2a88402cbe/build/85413075-38d4-497c-8521-ae10ab3eff32/task/smoke-test

**Comment by jayvdb** [comment]
Ping.  Running CI with 0 tests is a bit odd.

**Comment by freakboy3742** [comment]
Totally agreed. The current code is somewhat difficult to test, as setuptools doesn't provide an especially testable interface.

I'm currently working on a refactor of Briefcase (#266), and one of the major foci of this work is to introduce a test suite.

**Comment by freakboy3742** [comment]
The 0.3 branch now contains a comprehensive test suite 🎉

**Comment by jayvdb** [comment]
Thanks.  Tests all passing at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-briefcase

If the test suite is comprehensive, I believe the `GitPython==3.0.2` pin is too high -- at least the tests all pass on lower versions of GitPython.
