### ISSUE TITLE
Properly Escape User Generated Content for `pyproject.toml`

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#905]
**Describe the bug**
When creating a Briefcase project, the user specifies content such as formal name and description for the `pyproject.toml` file. This content may contain characters that are [reserved](https://toml.io/en/v0.3.0#string) for TOML.

If `pyproject.toml` is not valid, Briefcase will always immediately error.

```
❯ briefcase dev

Briefcase configuration error: Invalid pyproject.toml: Unescaped '\' in a string (at line 2, column 26)

Log saved to /home/user/tmp/beeware/formalname/briefcase.2022_10_07-11_14_05.dev.log
```

**To Reproduce**
Using `briefcase new`, include a literal backslash character, i.e. `\`, in the Formal Name or Description.

**Expected behavior**
A valid `pyproject.toml` file should always be created.

**Screenshots**

**Environment:**
 - Operating System: Ubuntu 22.04
 - Python version: 3.10.7
 - Software versions:
   - Briefcase: cec41018b861876453a9f8e922dc84bd4e095028

**Additional Information**
#898 is currently proposing to introduce [`tomli-w`](https://pypi.org/project/tomli-w/) to write an entire TOML file for a static web app. This package only exposes support for writing an entire TOML document. Something like [`tomlkit`](https://pypi.org/project/tomlkit/) exposes a larger API for creating parts of a TOML document.

**Comment by freakboy3742** [comment]
`tomlkit` would be one option; the other would be to add "toml-escaping" tags to the cookiecutter utilities, and use them in the `pyproject.toml` template. I suspect 'escaping' tags are going to be much easier to implement and maintain, given our use case - otherwise, `briefcase-template` will be a template repository that is used to generate a template `pyproject.toml` file that we rewrite to a final form. Given than our use case is really only at risk for a handful of TOML fields (`description` being the most notable), template re-writing feels a bit like overkill.
