### ISSUE TITLE
Add Option to Display Supported Platforms

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#906]
**Is your feature request related to a problem? Please describe.**
Briefcase help text does not include a clear method to show supported platforms.

This should be added as a proper option alongside `-f/--formats`.

**Describe the solution you'd like**
Add `--platforms` option to enumerate supported platforms.

**Describe alternatives you've considered**
If you run, for example, `briefcase run asdf`, a list of supported platforms are in fact printed.

**Comment by mhsmith** [comment]
As well as (or maybe instead of) creating a new option, how about including the list in the `--help` output? For example:
* `briefcase run --help` would include a list of platforms
* `briefcase run windows --help` would include a list of formats

That way the user doesn't have to remember any other options than `--help`.

**Comment by freakboy3742** [comment]
For anyone looking at this; #907 is a separate ticket in a closely related area.
